import { Form, Head } from '@inertiajs/react';
import Money from '../../Components/Money';

export default function DemoPayment({payment}:{payment:{id:string;orderNumber:string;amount:number;currency:string}}){
    return <main className="min-h-screen bg-raoza-primary px-5 py-10 text-raoza-cream md:py-16"><Head title="Demo payment — RAOZA"/><div className="mx-auto grid max-w-5xl overflow-hidden border border-raoza-cream/20 lg:grid-cols-[.9fr_1.1fr]">
        <section className="relative min-h-[300px] overflow-hidden border-b border-raoza-cream/20 p-7 lg:min-h-[620px] lg:border-b-0 lg:border-r lg:p-10"><div className="absolute -left-28 top-20 h-80 w-80 rounded-full border border-raoza-gold/45"/><div className="absolute left-28 top-48 h-52 w-52 rounded-full border border-raoza-cream/20"/><div className="absolute bottom-12 right-8 h-28 w-28 rounded-full bg-raoza-gold/15"/><p className="relative text-[10px] uppercase tracking-[.24em] text-raoza-gold">RAOZA / Local development</p><div className="relative mt-20 grid h-40 w-40 place-items-center rounded-full border border-raoza-cream/30 lg:mt-40 lg:h-52 lg:w-52"><div className="text-center"><p className="text-[10px] uppercase tracking-[.15em] text-raoza-cream/55">Order</p><p className="mt-2 text-sm font-semibold tracking-[.08em]">{payment.orderNumber}</p></div></div></section>
        <section className="flex flex-col justify-center bg-raoza-cream p-7 text-raoza-black md:p-10 lg:p-14"><p className="text-[10px] uppercase tracking-[.22em] text-raoza-secondary">Payment simulator</p><h1 className="mt-3 font-display text-5xl leading-none text-raoza-primary md:text-6xl">Choose a payment state.</h1><p className="mt-5 max-w-md text-sm leading-6 text-raoza-black/60">This development-only screen simulates the payment provider. No real payment is made and this route is unavailable when demo mode is disabled.</p><div className="my-8 flex items-center justify-between border-y border-raoza-primary/15 py-6"><span className="text-xs uppercase tracking-[.14em]">Amount</span><span className="font-display text-4xl text-raoza-primary"><Money amount={payment.amount}/></span></div><div className="grid gap-3"><Form action={`/demo/payments/${payment.id}`} method="post" disableWhileProcessing><input type="hidden" name="status" value="paid"/><button className="raoza-button w-full">Simulate successful payment</button></Form><Form action={`/demo/payments/${payment.id}`} method="post" disableWhileProcessing><input type="hidden" name="status" value="failed"/><button className="raoza-button raoza-button-outline w-full">Simulate failed payment</button></Form><Form action={`/demo/payments/${payment.id}`} method="post" disableWhileProcessing><input type="hidden" name="status" value="cancelled"/><button className="w-full px-5 py-4 text-xs font-semibold uppercase tracking-[.14em] text-raoza-black/55 underline decoration-raoza-primary/30 underline-offset-4">Simulate cancellation</button></Form></div><p className="mt-7 text-[10px] uppercase tracking-[.13em] text-raoza-black/40">Development utility · Not a production checkout</p></section>
    </div></main>;
}
