import { Head, router, useForm } from '@inertiajs/react';
import { useState } from 'react';
import AdminLayout from '../../../Layouts/AdminLayout';

const date = (value: string) => new Date(value).toLocaleString('nl-NL');

export default function InventoryIndex({ inventories, movements, filters }: any) {
    const [selected, setSelected] = useState<any>(null);
    const form = useForm({ delta: 1, type: 'stock_received', reason: '', note: '' });
    const submit = (event: React.FormEvent) => { event.preventDefault(); if (!selected) return; form.patch(`/admin/inventory/${selected.variant_id}`, { preserveScroll: true, onSuccess: () => { setSelected(null); form.reset(); } }); };
    return <AdminLayout><Head title="Inventory" />
        <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.18em] text-raoza-secondary">Inventory</p><h1 className="mt-2 font-display text-4xl text-raoza-primary sm:text-5xl">Stock control</h1><p className="mt-2 max-w-2xl text-sm opacity-65">On hand is physical stock. Reserved is committed to open orders. Available is what customers can still buy.</p></div><form onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); router.get('/admin/inventory', { q: data.get('q') }, { preserveState: true }); }} className="flex"><label htmlFor="inventory-search" className="sr-only">Search inventory</label><input id="inventory-search" name="q" defaultValue={filters?.q} className="min-h-11 border p-2" placeholder="Product or SKU" /><button className="bg-raoza-primary px-4 text-sm text-raoza-cream">Search</button></form></div>
        <section className="mt-7 overflow-x-auto border bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-raoza-primary text-raoza-cream"><tr><th className="p-3">Product / variant</th><th>SKU</th><th>On hand</th><th>Reserved</th><th>Available</th><th></th></tr></thead><tbody>{inventories.data.map((item: any) => { const available = item.quantity_on_hand - item.quantity_reserved; return <tr className="border-t" key={item.id}><td className="p-3"><b>{item.variant.product.name}</b></td><td>{item.variant.sku}</td><td>{item.quantity_on_hand}</td><td>{item.quantity_reserved}</td><td><span className={`inline-block min-w-10 px-2 py-1 text-center ${available === 0 ? 'bg-red-100 text-red-900' : available <= 5 ? 'bg-amber-100 text-amber-900' : 'bg-green-100 text-green-900'}`}>{available}</span></td><td><button onClick={() => { setSelected(item); form.setData({ delta: 1, type: 'stock_received', reason: '', note: '' }); }} className="min-h-11 px-3 underline">Adjust</button></td></tr>; })}</tbody></table></section>
        {selected && <section role="dialog" aria-modal="true" aria-labelledby="adjust-title" className="fixed inset-0 z-50 grid place-items-center bg-raoza-black/60 p-4"><form onSubmit={submit} className="w-full max-w-lg bg-raoza-cream p-6 shadow-2xl"><div className="flex justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-raoza-secondary">Safe stock movement</p><h2 id="adjust-title" className="mt-1 font-display text-3xl text-raoza-primary">Adjust {selected.variant.sku}</h2><p className="mt-2 text-sm opacity-60">Current on hand: {selected.quantity_on_hand} · Reserved: {selected.quantity_reserved}</p></div><button type="button" onClick={() => setSelected(null)} aria-label="Close inventory adjustment" className="h-11 w-11 border">×</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Adjustment quantity<input required type="number" className="mt-1 min-h-11 w-full border p-2" value={form.data.delta} onChange={e => form.setData('delta', Number(e.target.value))} /><span className="mt-1 block text-xs font-normal opacity-55">Use a positive number to add and a negative number to remove.</span></label><label className="text-sm font-medium">Movement type<select className="mt-1 min-h-11 w-full border p-2" value={form.data.type} onChange={e => form.setData('type', e.target.value)}><option value="stock_received">Stock received</option><option value="damaged">Damaged / written off</option><option value="manual_adjustment">Manual correction</option></select></label><label className="text-sm font-medium sm:col-span-2">Reason *<input required className="mt-1 min-h-11 w-full border p-2" value={form.data.reason} onChange={e => form.setData('reason', e.target.value)} placeholder="e.g. Supplier delivery 1042" /></label><label className="text-sm font-medium sm:col-span-2">Internal note<textarea className="mt-1 w-full border p-2" rows={3} value={form.data.note} onChange={e => form.setData('note', e.target.value)} /></label></div>{Object.keys(form.errors).length > 0 && <div role="alert" className="mt-4 border border-red-700/30 bg-red-50 p-3 text-sm text-red-900">{Object.values(form.errors)[0] as string}</div>}<button disabled={form.processing || form.data.delta === 0 || !form.data.reason} className="mt-5 min-h-12 w-full bg-raoza-primary text-sm text-raoza-cream disabled:opacity-40">{form.processing ? 'Recording…' : 'Record stock movement'}</button></form></section>}
        <section className="mt-10"><h2 className="font-display text-3xl text-raoza-primary">Recent stock movements</h2><div className="mt-4 overflow-x-auto border bg-white"><table className="w-full min-w-[800px] text-left text-sm"><thead><tr className="border-b"><th className="p-3">Date</th><th>Product</th><th>SKU</th><th>Type</th><th>Change</th><th>Reason / reference</th></tr></thead><tbody>{movements.map((movement: any) => <tr className="border-t" key={movement.id}><td className="p-3">{date(movement.created_at)}</td><td>{movement.variant.product.name}</td><td>{movement.variant.sku}</td><td>{String(movement.type).replaceAll('_', ' ')}</td><td className={movement.quantity > 0 ? 'text-green-800' : 'text-red-800'}>{movement.quantity > 0 ? '+' : ''}{movement.quantity}</td><td>{movement.note || `${movement.reference_type || ''} ${movement.reference_id || ''}` || '—'}</td></tr>)}</tbody></table></div></section>
    </AdminLayout>;
}
