import {Head, Link, router, useForm} from '@inertiajs/react';
import {useEffect, useMemo, useState} from 'react';
import AdminLayout from '../../../Layouts/AdminLayout';
const eur=(n:number)=>(n/100).toLocaleString('nl-NL',{style:'currency',currency:'EUR'});
const err=(e:any)=><>{Object.keys(e).length>0&&<p className="mt-2 text-sm text-red-700">{Object.values(e)[0] as string}</p>}</>;
export default function ProductShow({product,categories,collections}:any){
 const details=useForm({name:product.name,slug:product.slug,description:product.description||'',base_price:product.base_price,status:product.status,published_at:product.published_at?.slice(0,16)||'',seo_title:product.seo_title||'',seo_description:product.seo_description||'',canonical_url:product.canonical_url||'',indexable:product.indexable??true,category_ids:product.categories.map((x:any)=>x.id),collection_ids:product.collections.map((x:any)=>x.id)});
 const option=useForm({name:'',position:product.options.length+1});
 const variant=useForm({sku:'',price_override:'' as any,status:'active',option_value_ids:[] as number[],opening_stock:0});
 const image=useForm({images:[] as File[],alt_text:''});
 const generator=useForm({sku_prefix:`RZ-${product.slug.replace(/[^a-z0-9]/gi,'').slice(0,6).toUpperCase()}`,opening_stock:0,status:'active'});
 const [orderedImages,setOrderedImages]=useState<any[]>(product.images);
 const previews=useMemo(()=>image.data.images.map(file=>({name:file.name,url:URL.createObjectURL(file)})),[image.data.images]);
 useEffect(()=>setOrderedImages(product.images),[product.images]);
 const toggle=(key:'category_ids'|'collection_ids',id:number)=>{const xs=details.data[key] as number[];details.setData(key,xs.includes(id)?xs.filter(x=>x!==id):[...xs,id])};
 const choose=(optionId:number,valueId:number)=>{const optionValueIds=product.options.flatMap((o:any)=>o.values.map((v:any)=>({oid:o.id,vid:v.id})));const selected=variant.data.option_value_ids.filter(id=>optionValueIds.find((x:any)=>x.vid===id)?.oid!==optionId);variant.setData('option_value_ids',[...selected,valueId])};
 return <AdminLayout><Head title={`${product.name} — Product`}/>
  <div className="flex items-center justify-between gap-4"><div><Link href="/admin/products" className="text-sm underline">← Products</Link><h1 className="mt-2 font-display text-5xl text-raoza-primary">{product.name}</h1><p className="text-sm opacity-60">/{product.slug} · {product.variants.length} variants</p></div><a href={`/products/${product.slug}`} target="_blank" className="border px-4 py-2 text-sm">View storefront ↗</a></div>

  <div className="mt-8 grid gap-2 sm:grid-cols-3 lg:grid-cols-6">{[['01','Product',true],['02','Media',product.images.length>0],['03','Placement',product.categories.length+product.collections.length>0],['04','Options',product.options.length>0],['05','Variants',product.variants.length>0],['06','Publish',product.status==='active']].map(([n,label,done])=><div key={String(n)} className={`border p-3 text-xs ${done?'border-raoza-primary bg-white':'border-dashed border-raoza-primary/25 text-raoza-black/50'}`}><b>{n}</b><span className="ml-2">{label}</span><span className="float-right" aria-label={done?'Complete':'Incomplete'}>{done?'✓':'○'}</span></div>)}</div>

  <section className="mt-6 border bg-white p-5"><p className="text-xs uppercase tracking-widest text-raoza-secondary">01 · Product / 03 · Placement / 06 · Publishing</p><h2 className="mt-2 font-display text-2xl">Product details</h2><form onSubmit={e=>{e.preventDefault();details.patch(`/admin/products/${product.id}`)}} className="mt-4 grid gap-4 md:grid-cols-2">
   <label className="text-sm">Name<input className="mt-1 w-full border p-2" value={details.data.name} onChange={e=>details.setData('name',e.target.value)}/></label><label className="text-sm">Slug<input className="mt-1 w-full border p-2" value={details.data.slug} onChange={e=>details.setData('slug',e.target.value)}/></label>
   <label className="text-sm">Base price (€)<input type="number" min="0" step="0.01" inputMode="decimal" className="mt-1 w-full border p-2" value={(details.data.base_price/100).toFixed(2)} onChange={e=>details.setData('base_price',Math.round(+e.target.value*100))}/><span className="mt-1 block text-xs opacity-60">{eur(details.data.base_price)}</span></label><label className="text-sm">Status<select className="mt-1 w-full border p-2" value={details.data.status} onChange={e=>details.setData('status',e.target.value)}><option value="draft">Draft</option><option value="active">Active</option><option value="archived">Archived</option></select></label>
   {details.data.status==='active'&&<label className="text-sm">Published at<input type="datetime-local" className="mt-1 w-full border p-2" value={details.data.published_at} onChange={e=>details.setData('published_at',e.target.value)}/></label>}
   <label className="md:col-span-2 text-sm">Description<textarea rows={4} className="mt-1 w-full border p-2" value={details.data.description} onChange={e=>details.setData('description',e.target.value)}/></label>
   <div><p className="mb-2 text-sm font-semibold">Categories</p>{categories.map((x:any)=><label key={x.id} className="mr-4 inline-flex gap-2 text-sm"><input type="checkbox" checked={details.data.category_ids.includes(x.id)} onChange={()=>toggle('category_ids',x.id)}/>{x.name}</label>)}</div>
   <div><p className="mb-2 text-sm font-semibold">Collections</p>{collections.map((x:any)=><label key={x.id} className="mr-4 inline-flex gap-2 text-sm"><input type="checkbox" checked={details.data.collection_ids.includes(x.id)} onChange={()=>toggle('collection_ids',x.id)}/>{x.name}</label>)}</div>
   <label className="text-sm">SEO title<input className="mt-1 w-full border p-2" value={details.data.seo_title} onChange={e=>details.setData('seo_title',e.target.value)}/></label><label className="text-sm">SEO description<input className="mt-1 w-full border p-2" value={details.data.seo_description} onChange={e=>details.setData('seo_description',e.target.value)}/></label><label className="text-sm">Canonical URL<input type="url" className="mt-1 w-full border p-2" value={details.data.canonical_url} onChange={e=>details.setData('canonical_url',e.target.value)}/></label><label className="flex items-center gap-2 self-end py-2 text-sm"><input type="checkbox" checked={details.data.indexable} onChange={e=>details.setData('indexable',e.target.checked)}/>Allow search indexing</label>
   <div className="md:col-span-2"><button disabled={details.processing} className="bg-raoza-primary px-5 py-2 text-raoza-cream disabled:opacity-50">Save product</button>{err(details.errors)}</div>
  </form></section>

  <section className="mt-6 border bg-white p-5"><h2 className="font-display text-2xl">Options & values</h2><div className="mt-4 grid gap-5 lg:grid-cols-2"><div>{product.options.map((o:any)=><OptionBlock key={o.id} product={product} option={o}/>)}</div><form onSubmit={e=>{e.preventDefault();option.post(`/admin/products/${product.id}/options`,{onSuccess:()=>option.reset('name')})}} className="h-fit border p-4"><p className="font-semibold">Add option</p><div className="mt-3 flex gap-2"><input className="min-w-0 flex-1 border p-2" placeholder="e.g. Size or Color" value={option.data.name} onChange={e=>option.setData('name',e.target.value)}/><button className="border px-4">Add</button></div>{err(option.errors)}</form></div></section>

  <section className="mt-6 border bg-white p-5"><p className="text-xs uppercase tracking-widest text-raoza-secondary">05 · Inventory</p><h2 className="mt-2 font-display text-2xl">Variants & opening stock</h2>{product.options.length===0?<p className="mt-3 text-sm">Create at least one option before creating variants.</p>:<><form onSubmit={e=>{e.preventDefault();generator.post(`/admin/products/${product.id}/variants/generate`,{preserveScroll:true})}} className="mt-4 border border-raoza-gold/60 bg-raoza-cream/40 p-4"><h3 className="font-semibold">Generate missing combinations</h3><p className="mt-1 text-xs opacity-65">Creates every missing option combination with unique SKUs and an auditable opening-stock movement.</p><div className="mt-3 grid gap-3 sm:grid-cols-3"><label className="text-xs">SKU prefix<input className="mt-1 w-full border p-2" value={generator.data.sku_prefix} onChange={e=>generator.setData('sku_prefix',e.target.value)}/></label><label className="text-xs">Opening stock per variant<input className="mt-1 w-full border p-2" type="number" min="0" value={generator.data.opening_stock} onChange={e=>generator.setData('opening_stock',+e.target.value)}/></label><button disabled={generator.processing} className="self-end bg-raoza-primary px-4 py-2 text-sm text-raoza-cream disabled:opacity-50">{generator.processing?'Generating…':'Generate combinations'}</button></div>{err(generator.errors)}</form><form onSubmit={e=>{e.preventDefault();variant.post(`/admin/products/${product.id}/variants`,{onSuccess:()=>variant.reset()})}} className="mt-4 border p-4"><h3 className="font-semibold">Create one custom variant</h3><div className="mt-3 grid gap-4 md:grid-cols-2">{product.options.map((o:any)=><div key={o.id}><p className="mb-2 text-sm font-semibold">{o.name}</p><div className="flex flex-wrap gap-2">{o.values.map((v:any)=><button type="button" key={v.id} onClick={()=>choose(o.id,v.id)} className={`border px-3 py-1.5 text-sm ${variant.data.option_value_ids.includes(v.id)?'bg-raoza-primary text-raoza-cream':''}`}>{v.value}</button>)}</div></div>)}</div><div className="mt-4 grid gap-3 md:grid-cols-4"><input className="border p-2" placeholder="SKU" value={variant.data.sku} onChange={e=>variant.setData('sku',e.target.value)}/><input className="border p-2" type="number" min="0" step="0.01" inputMode="decimal" placeholder="Price override (€)" value={variant.data.price_override===''?'':(Number(variant.data.price_override)/100).toFixed(2)} onChange={e=>variant.setData('price_override',e.target.value===''?'':Math.round(+e.target.value*100))}/><input className="border p-2" type="number" min="0" placeholder="Opening stock" value={variant.data.opening_stock} onChange={e=>variant.setData('opening_stock',+e.target.value)}/><button disabled={variant.processing} className="bg-raoza-primary px-4 text-raoza-cream">Create variant</button></div>{err(variant.errors)}</form></>}
   <div className="mt-5 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">Variant</th><th>SKU</th><th>Price</th><th>On hand</th><th>Reserved</th><th>Available</th><th>Status</th></tr></thead><tbody>{product.variants.map((v:any)=><VariantRow key={v.id} product={product} variant={v}/>)}</tbody></table></div>
  </section>

  <section className="mt-6 border bg-white p-5"><p className="text-xs uppercase tracking-widest text-raoza-secondary">02 · Media</p><h2 className="mt-2 font-display text-2xl">Product images</h2><p className="mt-1 text-sm opacity-65">Upload JPG, PNG or WebP files up to 5 MB. The first image is the primary storefront image.</p><form onSubmit={e=>{e.preventDefault();image.post(`/admin/products/${product.id}/images`,{forceFormData:true,preserveScroll:true,onSuccess:()=>image.reset()})}} className="mt-4 border border-dashed border-raoza-primary/30 p-4"><label className="block text-sm font-semibold">Choose images<input type="file" multiple accept="image/jpeg,image/png,image/webp" className="mt-2 block w-full text-sm" onChange={e=>image.setData('images',Array.from(e.target.files||[]))}/></label>{previews.length>0&&<div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{previews.map(preview=><div key={preview.url}><img src={preview.url} alt="Upload preview" className="aspect-[4/5] w-full object-cover"/><p className="mt-1 truncate text-xs">{preview.name}</p></div>)}</div>}<div className="mt-4 flex flex-wrap gap-3"><input className="min-h-11 flex-1 border p-2 text-sm" placeholder="Alt text (defaults to product name)" value={image.data.alt_text} onChange={e=>image.setData('alt_text',e.target.value)}/><button disabled={image.processing||image.data.images.length===0} className="min-h-11 bg-raoza-primary px-5 text-sm text-raoza-cream disabled:opacity-40">{image.processing?`Uploading ${image.progress?.percentage??0}%`:'Upload images'}</button></div>{err(image.errors)}</form><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{orderedImages.map((x:any,index:number)=><div key={x.id} className="border p-3"><div className="mb-2 flex items-center justify-between text-xs"><b>{index===0?'Primary image':`Image ${index+1}`}</b><div><button disabled={index===0} aria-label="Move image left" onClick={()=>setOrderedImages(xs=>{const n=[...xs];[n[index-1],n[index]]=[n[index],n[index-1]];return n})} className="px-2 disabled:opacity-25">←</button><button disabled={index===orderedImages.length-1} aria-label="Move image right" onClick={()=>setOrderedImages(xs=>{const n=[...xs];[n[index+1],n[index]]=[n[index],n[index+1]];return n})} className="px-2 disabled:opacity-25">→</button></div></div><img src={imageUrl(x.path)} alt={x.alt_text||''} className="aspect-[4/5] w-full bg-raoza-cream object-cover"/><p className="mt-2 truncate text-xs">{x.alt_text||x.path}</p><div className="mt-2 flex justify-between"><button onClick={()=>router.patch(`/admin/products/${product.id}/images/reorder`,{image_ids:orderedImages.map(i=>i.id)},{preserveScroll:true})} className="text-xs underline">Save order</button><button onClick={()=>confirm('Remove this image?')&&router.delete(`/admin/products/${product.id}/images/${x.id}`,{preserveScroll:true})} className="text-xs text-red-800 underline">Remove</button></div></div>)}</div></section>
 </AdminLayout>
}
const imageUrl=(path:string)=>path.startsWith('http')||path.startsWith('/')?path:`/storage/${path}`;
function OptionBlock({product,option}:any){const f=useForm({value:'',swatch:''});const used=option.values.some((v:any)=>v.variants_count>0);return <div className="mb-4 border p-4"><div className="flex items-center justify-between gap-3"><div className="font-semibold">{option.name}</div>{!used&&<button type="button" onClick={()=>confirm(`Remove the unused ${option.name} option?`)&&router.delete(`/admin/products/${product.id}/options/${option.id}`,{preserveScroll:true})} className="text-xs text-red-800 underline">Remove option</button>}</div><div className="mt-2 flex flex-wrap gap-2">{option.values.map((v:any)=><span key={v.id} className="inline-flex items-center gap-2 border px-2 py-1 text-sm">{v.metadata?.swatch&&<i className="h-3 w-3 rounded-full border" style={{background:v.metadata.swatch}}/>}{v.value}{v.variants_count===0&&<button type="button" aria-label={`Remove unused value ${v.value}`} onClick={()=>confirm(`Remove the unused value ${v.value}?`)&&router.delete(`/admin/products/${product.id}/options/${option.id}/values/${v.id}`,{preserveScroll:true})} className="ml-1 text-red-800">×</button>}</span>)}</div><form onSubmit={e=>{e.preventDefault();f.post(`/admin/products/${product.id}/options/${option.id}/values`,{onSuccess:()=>f.reset()})}} className="mt-3 flex flex-wrap gap-2"><input className="border p-2" placeholder="Value" value={f.data.value} onChange={e=>f.setData('value',e.target.value)}/><input className="w-32 border p-2" placeholder="#330313" value={f.data.swatch} onChange={e=>f.setData('swatch',e.target.value)}/><button className="border px-3">Add value</button></form>{err(f.errors)}</div>}
function VariantRow({product,variant}:any){const f=useForm({sku:variant.sku,price_override:variant.price_override??'',status:variant.status});const label=variant.option_values?.map((x:any)=>x.value).join(' / ')||'—';const inv=variant.inventory;return <tr className="border-b"><td className="p-2">{label}</td><td><input className="w-36 border p-1" aria-label={`SKU for ${label}`} value={f.data.sku} onChange={e=>f.setData('sku',e.target.value)}/></td><td><input className="w-24 border p-1" aria-label={`Price override for ${label} in euros`} type="number" min="0" step="0.01" inputMode="decimal" placeholder={(product.base_price/100).toFixed(2)} value={f.data.price_override===''?'':(Number(f.data.price_override)/100).toFixed(2)} onChange={e=>f.setData('price_override',e.target.value===''?'':Math.round(+e.target.value*100))}/></td><td>{inv?.quantity_on_hand??0}</td><td>{inv?.quantity_reserved??0}</td><td>{inv?(inv.quantity_on_hand-inv.quantity_reserved):0}</td><td><select aria-label={`Status for ${label}`} className="border p-1" value={f.data.status} onChange={e=>f.setData('status',e.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option></select><button onClick={()=>f.patch(`/admin/products/${product.id}/variants/${variant.id}`)} disabled={f.processing} className="ml-2 underline">Save</button></td></tr>}
