<?php
namespace App\Domain\Fulfillment\Services;
use App\Domain\Commerce\Enums\FulfillmentStatus;
use App\Domain\Commerce\Enums\PaymentStatus;
use App\Domain\Commerce\Models\Order;
use App\Domain\Fulfillment\Enums\ShipmentStatus;
use App\Domain\Fulfillment\Models\Shipment;
use Illuminate\Support\Facades\DB;
use RuntimeException;
class FulfillmentService {
 private const NEXT=['unfulfilled'=>['processing'],'processing'=>['printing','on_hold'],'printing'=>['ready_to_ship','on_hold'],'ready_to_ship'=>['fulfilled','on_hold'],'on_hold'=>['processing','printing','ready_to_ship','cancelled'],'fulfilled'=>[],'cancelled'=>[]];
 public function transition(Order $order,FulfillmentStatus $to,?int $actorId=null,?string $reason=null):Order{return DB::transaction(function()use($order,$to,$actorId,$reason){$o=Order::whereKey($order->id)->lockForUpdate()->firstOrFail();if(!$o->payment_status->allowsFulfillment())throw new RuntimeException('Only paid or partially refunded orders can enter fulfillment.');$from=$o->fulfillment_status;if(!in_array($to->value,self::NEXT[$from->value]??[],true))throw new RuntimeException("Invalid fulfillment transition: {$from->value} -> {$to->value}.");$o->update(['fulfillment_status'=>$to]);$o->statusHistory()->create(['domain'=>'fulfillment','from_status'=>$from->value,'to_status'=>$to->value,'reason'=>$reason,'actor_user_id'=>$actorId,'created_at'=>now()]);return $o->refresh();},3);}
 public function createManualShipment(Order $order,array $data,int $actorId):Shipment{return DB::transaction(function()use($order,$data,$actorId){$o=Order::whereKey($order->id)->lockForUpdate()->firstOrFail();if(!$o->payment_status->allowsFulfillment())throw new RuntimeException('Cannot ship an unpaid or fully refunded order.');if(!in_array($o->fulfillment_status,[FulfillmentStatus::ReadyToShip,FulfillmentStatus::Fulfilled],true))throw new RuntimeException('Order must be ready to ship.');$o->loadMissing('items');$shipment=Shipment::create(['order_id'=>$o->id,'provider'=>'manual','status'=>ShipmentStatus::Shipped,'tracking_number'=>$data['tracking_number']??null,'tracking_url'=>$data['tracking_url']??null,'shipping_cost'=>$o->shipping_amount,'currency'=>$o->currency,'shipped_at'=>now()]);foreach($o->items as $item){$already=(int)$item->shipmentItems()->sum('quantity');$remaining=$item->quantity-$already;if($remaining>0)$shipment->items()->create(['order_item_id'=>$item->id,'quantity'=>$remaining]);}$shipment->events()->create(['status'=>'shipped','description'=>'Shipment marked as shipped by admin.','occurred_at'=>now(),'created_at'=>now()]);if($o->fulfillment_status===FulfillmentStatus::ReadyToShip)$this->transitionLocked($o,FulfillmentStatus::Fulfilled,$actorId,'shipment_created');return $shipment->load('items');},3);}
 private function transitionLocked(Order $o,FulfillmentStatus $to,?int $actorId,string $reason):void{$from=$o->fulfillment_status;$o->update(['fulfillment_status'=>$to]);$o->statusHistory()->create(['domain'=>'fulfillment','from_status'=>$from->value,'to_status'=>$to->value,'reason'=>$reason,'actor_user_id'=>$actorId,'created_at'=>now()]);}
}
