import { Head, Link, router, usePage } from '@inertiajs/react';
import { useState } from 'react';
import Money from '../../Components/Money';
import StorefrontLayout from '../../Layouts/StorefrontLayout';

type Item={id:number;variantId:number;productName:string;productSlug:string;sku:string;options:Record<string,string>;quantity:number;unitPrice:number;lineTotal:number;availableQuantity:number;valid:boolean;image:string|null;imageAlt:string};
type Cart={currency:string;count:number;subtotal:number;valid:boolean;items:Item[]};
export default function CartPage({cart}:{cart:Cart}){
 const page=usePage<{errors?:Record<string,string>;flash?:{success?:string}}>();
 const [busy,setBusy]=useState<number|null>(null);
 const update=(id:number,quantity:number)=>{setBusy(id);router.patch(`/cart/items/${id}`,{quantity},{preserveScroll:true,onFinish:()=>setBusy(null)})};
 const remove=(id:number)=>{setBusy(id);router.delete(`/cart/items/${id}`,{preserveScroll:true,onFinish:()=>setBusy(null)})};
 return <StorefrontLayout><Head title="Bag — RAOZA"><meta name="robots" content="noindex,nofollow"/></Head><main className="raoza-commerce-page"><div className="raoza-commerce-shell"><header className="raoza-commerce-header"><div><p className="raoza-eyebrow">RAOZA / Bag</p><h1>Your bag</h1></div><span>{String(cart.count).padStart(2,'0')} / ITEMS</span></header>
 {(page.props.errors?.quantity||page.props.errors?.variant)&&<div role="alert" className="raoza-commerce-alert">{page.props.errors.quantity||page.props.errors.variant}</div>}
 {cart.items.length===0?<section className="raoza-empty-bag"><div className="raoza-empty-orbit"><span>0</span></div><p>Your bag is empty.</p><Link href="/shop" className="raoza-button raoza-button-outline">Explore the shop</Link></section>:<div className="raoza-cart-layout"><section className="raoza-cart-list">{cart.items.map((item,index)=><article key={item.id} className={`raoza-cart-item ${busy===item.id?'is-busy':''}`} aria-busy={busy===item.id}><div className="raoza-cart-orbit"><span className="raoza-cart-index">{String(index+1).padStart(2,'0')}</span><Link href={`/products/${item.productSlug}`} className="raoza-cart-image">{item.image?<img src={item.image} alt={item.imageAlt}/>:<span>RAOZA</span>}</Link></div><div className="raoza-cart-copy"><p className="raoza-eyebrow">{item.sku}</p><Link href={`/products/${item.productSlug}`} className="raoza-cart-name">{item.productName}</Link><p className="raoza-cart-options">{Object.entries(item.options).map(([k,v])=>`${k}: ${v}`).join(' · ')}</p>{!item.valid&&<p className="raoza-cart-stock" role="alert">Quantity or availability changed. {item.availableQuantity} currently available.</p>}{item.valid&&item.availableQuantity<=3&&<p className="raoza-cart-stock">Only {item.availableQuantity} left.</p>}<div className="raoza-cart-actions"><label htmlFor={`qty-${item.id}`}>Qty</label><select disabled={busy===item.id||item.availableQuantity<1} id={`qty-${item.id}`} value={item.quantity} onChange={e=>update(item.id,Number(e.target.value))}>{Array.from({length:Math.min(20,Math.max(item.availableQuantity,item.quantity))},(_,i)=>i+1).map(q=><option key={q} value={q}>{q}</option>)}</select><button type="button" disabled={busy===item.id} onClick={()=>remove(item.id)}>Remove</button></div></div><div className="raoza-cart-price"><Money amount={item.lineTotal}/></div></article>)}</section><aside className="raoza-cart-summary"><div className="raoza-summary-number">{String(cart.count).padStart(2,'0')}</div><p className="raoza-eyebrow">Order summary</p><h2>Ready when you are.</h2><div className="raoza-summary-row"><span>Subtotal</span><Money amount={cart.subtotal}/></div><p className="raoza-summary-note">Shipping and final totals are calculated securely during checkout.</p><Link href="/checkout" aria-disabled={!cart.valid} className={`raoza-button raoza-summary-cta ${!cart.valid?'is-disabled':''}`}>Continue to checkout</Link>{!cart.valid&&<p className="raoza-cart-stock">Resolve unavailable quantities before checkout.</p>}<Link href="/shop" className="raoza-summary-back">Continue shopping</Link></aside></div>}</div></main></StorefrontLayout>;
}
