import { Form, Head, Link } from '@inertiajs/react';
import { useMemo, useState } from 'react';
import Money from '../../Components/Money';
import StorefrontLayout from '../../Layouts/StorefrontLayout';

type Item = { id: number; productName: string; options: Record<string, string>; quantity: number; lineTotal: number; valid: boolean; image?: string | null; imageAlt?: string };
type Cart = { currency: string; count: number; subtotal: number; valid: boolean; items: Item[] };
type Shipping = { id: number; name: string; code: string; price: number; description?: string | null };
type CheckoutPayload = { cart: Cart; shippingMethods: Shipping[]; vatRateBasisPoints: number; demoMode: boolean };
const input = 'raoza-checkout-input';

export default function Checkout({ checkout }: { checkout: CheckoutPayload }) {
 const [same,setSame]=useState(true); const [shipping,setShipping]=useState(checkout.shippingMethods[0]?.id??0);
 const selected=useMemo(()=>checkout.shippingMethods.find(method=>method.id===shipping),[shipping,checkout.shippingMethods]);
 const estimatedTotal=checkout.cart.subtotal+(selected?.price??0);
 const field=(name:string,label:string,required=true,autoComplete?:string)=><label className="raoza-checkout-field"><span>{label}</span><input name={name} required={required} autoComplete={autoComplete} className={input}/></label>;
 return <StorefrontLayout><Head title="Checkout — RAOZA"/><main className="raoza-commerce-page"><div className="raoza-commerce-shell"><header className="raoza-commerce-header"><div><p className="raoza-eyebrow">RAOZA / Secure checkout</p><h1>Checkout</h1></div><span>SECURE / NL</span></header>{checkout.demoMode&&<p className="raoza-demo-note">Demo mode is active. No real money is charged.</p>}
 <Form action="/checkout" method="post" className="raoza-checkout-layout" disableWhileProcessing>{({errors,processing})=><><section className="raoza-checkout-form"><CheckoutSection number="01" title="Contact"><div className="raoza-field-grid">{field('email','Email',true,'email')}{field('phone','Phone',false,'tel')}</div></CheckoutSection><CheckoutSection number="02" title="Shipping address"><Address prefix="shipping_" field={field}/></CheckoutSection><CheckoutSection number="03" title="Delivery"><div className="raoza-delivery-list">{checkout.shippingMethods.map(method=><label key={method.id} className={`raoza-delivery-card ${shipping===method.id?'is-selected':''}`}><input type="radio" name="shipping_method_id" value={method.id} checked={shipping===method.id} onChange={()=>setShipping(method.id)}/><span className="raoza-delivery-dot"/><span className="raoza-delivery-copy"><strong>{method.name}</strong>{method.description&&<small>{method.description}</small>}</span><Money amount={method.price}/></label>)}{checkout.shippingMethods.length===0&&<p className="raoza-commerce-alert">No delivery method is currently available. Checkout cannot continue.</p>}</div></CheckoutSection><section className="raoza-billing-toggle"><input type="hidden" name="billing_same_as_shipping" value="0"/><label><input type="checkbox" name="billing_same_as_shipping" value="1" checked={same} onChange={e=>setSame(e.target.checked)}/><span>Billing address is the same as shipping</span></label></section>{!same&&<CheckoutSection number="04" title="Billing address"><Address prefix="billing_" field={field}/></CheckoutSection>}{Object.keys(errors).length>0&&<div role="alert" className="raoza-commerce-alert"><strong>Please review the checkout information.</strong>{Object.entries(errors).map(([key,value])=><p key={key}>{value}</p>)}</div>}<p className="raoza-checkout-legal">Prices are VAT-inclusive. Product availability, discount, delivery, VAT component and final total are recalculated by the server before the order is created.</p></section>
 <aside className="raoza-checkout-summary"><div className="raoza-checkout-orbit" aria-hidden="true"><span>{String(checkout.cart.count).padStart(2,'0')}</span></div><p className="raoza-eyebrow">Your selection</p><h2>Order summary</h2><div className="raoza-checkout-products">{checkout.cart.items.map((item,index)=><div key={item.id} className="raoza-checkout-product">{item.image?<div className="raoza-checkout-product-image"><img src={item.image} alt={item.imageAlt??item.productName}/></div>:<span className="raoza-checkout-product-index">{String(index+1).padStart(2,'0')}</span>}<div><p>{item.productName} × {item.quantity}</p><small>{Object.values(item.options).join(' · ')}</small></div><Money amount={item.lineTotal}/></div>)}</div><div className="raoza-checkout-totals"><div><span>Subtotal</span><Money amount={checkout.cart.subtotal}/></div><div><span>{selected?.name??'Delivery'}</span><Money amount={selected?.price??0}/></div><div className="is-total"><span>Estimated total</span><Money amount={estimatedTotal}/></div></div><label className="raoza-checkout-field raoza-discount"><span>Discount code</span><input name="discount_code" autoCapitalize="characters" placeholder={checkout.demoMode?'WELCOME10 / RAOZA5':''} className={input}/></label><p className="raoza-summary-note">Valid discounts are applied by the server before payment.</p><button disabled={processing||!checkout.cart.valid||!shipping||checkout.shippingMethods.length===0} className="raoza-button raoza-summary-cta disabled:cursor-not-allowed disabled:opacity-45">{processing?'Creating order…':'Continue to payment'}</button><Link href="/cart" className="raoza-summary-back">Back to bag</Link></aside></>}</Form></div></main></StorefrontLayout>;
}
function CheckoutSection({number,title,children}:{number:string;title:string;children:React.ReactNode}){return <section className="raoza-checkout-section"><header><span>{number}</span><h2>{title}</h2></header>{children}</section>}
function Address({prefix,field}:{prefix:string;field:(name:string,label:string,required?:boolean,autoComplete?:string)=>React.ReactElement}){const shipping=prefix==='shipping_';const ac=(value:string)=>shipping?`shipping ${value}`:`billing ${value}`;return <div className="raoza-field-grid">{field(prefix+'first_name','First name',true,ac('given-name'))}{field(prefix+'last_name','Last name',true,ac('family-name'))}<div className="sm:col-span-2">{field(prefix+'company','Company',false,ac('organization'))}</div><div className="sm:col-span-2">{field(prefix+'street','Street',true,ac('address-line1'))}</div>{field(prefix+'house_number','House number')}{field(prefix+'addition','Addition',false,ac('address-line2'))}{field(prefix+'postal_code','Postal code',true,ac('postal-code'))}{field(prefix+'city','City',true,ac('address-level2'))}<label className="raoza-checkout-field sm:col-span-2"><span>Country</span><select name={prefix+'country_code'} defaultValue="NL" autoComplete={ac('country')} className={input}><option value="NL">Netherlands</option></select></label></div>}
