import { Link } from '@inertiajs/react';
import SeoHead, { Seo } from '../../Components/SeoHead';
import ProductCard, { ProductCardData } from '../../Components/ProductCard';
import StorefrontLayout from '../../Layouts/StorefrontLayout';
type Collection={id:number;name:string;slug:string;description:string|null};
export default function Home({featuredProducts,collections,seo}:{featuredProducts:ProductCardData[];collections:Collection[];seo:Seo}){const leadCollection=collections[0];return <StorefrontLayout><SeoHead seo={seo}/>
 <main>
  <section className="border-b border-raoza-primary/15"><div className="mx-auto grid max-w-[1500px] lg:min-h-[calc(100svh-108px)] lg:grid-cols-[1.04fr_.96fr]">
   <div className="flex flex-col justify-center px-5 py-16 md:px-10 md:py-20 lg:py-24"><p className="raoza-eyebrow mb-7">Urban editorial · Drop by drop</p><h1 className="max-w-4xl font-display text-[clamp(3.7rem,8vw,8.8rem)] leading-[.82] tracking-[-.05em] text-raoza-primary">Wear the<br/><span className="italic">attitude.</span></h1><p className="mt-9 max-w-md text-sm leading-7 text-raoza-black/65">A curated line of printed T-shirts and hoodies built around graphic expression, clean silhouettes and confident everyday wear.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/shop" className="raoza-button">Shop the edit</Link>{leadCollection&&<Link href={`/collections/${leadCollection.slug}`} className="raoza-button raoza-button-outline">Explore collection</Link>}</div></div>
   <div className="relative min-h-[58svh] overflow-hidden bg-raoza-primary text-raoza-cream lg:min-h-0"><div className="absolute -right-10 top-4 font-display text-[11rem] italic leading-none text-raoza-cream/[.035] md:text-[17rem]">R</div><div className="relative flex h-full min-h-[520px] flex-col justify-between p-6 md:p-10"><div className="flex items-center justify-between border-b border-raoza-cream/20 pb-5 text-[9px] uppercase tracking-[.23em]"><span className="text-raoza-gold">RAOZA / 001</span><span className="text-raoza-cream/55">Printed apparel</span></div><div className="max-w-xl"><p className="font-display text-[clamp(3.5rem,7vw,7rem)] leading-[.86] tracking-[-.045em]">Modern.<br/>Graphic.<br/><span className="italic text-raoza-gold">Unforced.</span></p><p className="mt-7 max-w-sm text-sm leading-7 text-raoza-cream/65">Designed as a label, not a catalogue: fewer pieces, stronger direction, a visual language built to evolve.</p></div><div className="flex items-end justify-between border-t border-raoza-cream/20 pt-5 text-[9px] uppercase tracking-[.2em] text-raoza-cream/50"><span>Deep Burgundy<br/>Warm Cream</span><span className="text-right">NL / 2026<br/>Urban Editorial</span></div></div></div>
  </div></section>
  <section className="mx-auto max-w-[1500px] px-5 py-20 md:px-10 md:py-28"><div className="mb-10 flex items-end justify-between gap-6"><div><p className="raoza-eyebrow">Selected pieces</p><h2 className="mt-3 font-display text-4xl text-raoza-primary md:text-6xl">The current <span className="italic">edit.</span></h2></div><Link href="/shop" className="hidden text-[10px] font-semibold uppercase tracking-[.17em] underline underline-offset-8 sm:block">View all pieces</Link></div>{featuredProducts.length?<div className="grid grid-cols-2 gap-x-4 gap-y-12 lg:grid-cols-4 lg:gap-x-6">{featuredProducts.map((p,i)=><ProductCard key={p.id} product={p} priority={i<2}/>)}</div>:<div className="border-y border-raoza-primary/15 py-20 text-center"><p className="font-display text-3xl text-raoza-primary">This edit is currently unavailable.</p><p className="mt-3 text-sm text-raoza-black/55">Browse the shop to explore the active RAOZA selection.</p></div>}<Link href="/shop" className="raoza-button raoza-button-outline mt-10 w-full sm:hidden">View all pieces</Link></section>
  <section className="bg-raoza-black text-raoza-cream"><div className="mx-auto grid max-w-[1500px] gap-12 px-5 py-20 md:px-10 md:py-28 lg:grid-cols-[1.15fr_.85fr]"><div><p className="text-[9px] uppercase tracking-[.24em] text-raoza-gold">The RAOZA position</p><p className="mt-5 font-display text-5xl leading-[.92] md:text-7xl">Not a print shop.<br/><span className="italic text-raoza-gold">A point of view.</span></p></div><div className="flex max-w-lg flex-col justify-end"><p className="text-base leading-8 text-raoza-cream/70">RAOZA is built as a design-led apparel label: a controlled product selection, considered graphics and a visual identity that can grow beyond the first printed pieces.</p><Link href="/pages/about" className="mt-7 w-fit border-b border-raoza-cream/50 pb-2 text-[10px] font-semibold uppercase tracking-[.18em]">About RAOZA</Link></div></div></section>
  {collections.length>0&&<section className="mx-auto max-w-[1500px] px-5 py-20 md:px-10 md:py-28"><div className="flex items-end justify-between"><div><p className="raoza-eyebrow">Collections</p><h2 className="mt-3 font-display text-4xl text-raoza-primary md:text-6xl">Shop by <span className="italic">story.</span></h2></div><span className="hidden text-[9px] uppercase tracking-[.18em] text-raoza-black/45 md:block">Curated selection</span></div><div className="mt-10 grid gap-px bg-raoza-primary/20 md:grid-cols-3">{collections.map((c,i)=><Link key={c.id} href={`/collections/${c.slug}`} className="group flex min-h-80 flex-col justify-between bg-raoza-cream p-7 transition-colors hover:bg-raoza-primary hover:text-raoza-cream md:p-8"><div className="flex justify-between text-[9px] uppercase tracking-[.18em]"><span>0{i+1}</span><span>Collection</span></div><div><h3 className="font-display text-4xl text-raoza-primary transition-colors group-hover:text-raoza-cream md:text-5xl">{c.name}</h3>{c.description&&<p className="mt-4 max-w-sm text-sm leading-6 text-raoza-black/55 group-hover:text-raoza-cream/65">{c.description}</p>}<span className="mt-6 block text-[10px] font-semibold uppercase tracking-[.17em]">Explore →</span></div></Link>)}</div></section>}
 </main></StorefrontLayout>}
