import { Link } from '@inertiajs/react';
import SeoHead, { Seo } from '../../Components/SeoHead';
import ProductCard, { ProductCardData } from '../../Components/ProductCard';
import StorefrontLayout from '../../Layouts/StorefrontLayout';
type Collection={id:number;name:string;slug:string;description:string|null};
export default function Home({featuredProducts,collections,seo}:{featuredProducts:ProductCardData[];collections:Collection[];seo:Seo}){return <StorefrontLayout><SeoHead seo={seo} />
 <main>
  <section className="border-b border-raoza-primary/15"><div className="mx-auto grid min-h-[calc(100svh-108px)] max-w-[1500px] lg:grid-cols-[1.05fr_.95fr]">
   <div className="flex flex-col justify-center px-5 py-14 md:px-10 lg:py-24"><p className="mb-7 text-[11px] font-semibold uppercase tracking-[.25em] text-raoza-secondary">Urban editorial · Drop by drop</p><h1 className="max-w-4xl font-display text-[clamp(3.6rem,8vw,8.8rem)] leading-[.82] tracking-[-.045em] text-raoza-primary">Wear the<br/><span className="italic">attitude.</span></h1><p className="mt-9 max-w-md text-sm leading-7 text-raoza-black/65">A curated line of printed T-shirts and hoodies built around graphic expression, clean silhouettes and confident everyday wear.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/shop" className="raoza-button">Shop the edit</Link><Link href="/collections/drop-01" className="raoza-button raoza-button-outline">Collections</Link></div></div>
   <div className="min-h-[50vh] bg-raoza-primary p-6 text-raoza-cream md:p-10"><div className="flex h-full min-h-[480px] flex-col justify-between border border-raoza-cream/25 p-7 md:p-10"><span className="text-[10px] uppercase tracking-[.25em] text-raoza-gold">RAOZA / Apparel</span><div><p className="font-display text-5xl leading-[.92] md:text-7xl">Modern.<br/>Graphic.<br/><span className="italic">Unforced.</span></p><p className="mt-7 max-w-xs text-sm leading-6 text-raoza-cream/65">This campaign panel establishes the RAOZA art direction. Seeded product cards use clearly marked demo artwork until real photography replaces it.</p></div><span className="text-[10px] uppercase tracking-[.2em] text-raoza-cream/50">Deep Burgundy / Warm Cream</span></div></div>
  </div></section>
  <section className="mx-auto max-w-[1500px] px-5 py-20 md:px-10"><div className="mb-10 flex items-end justify-between gap-6"><div><p className="text-[10px] uppercase tracking-[.22em] text-raoza-secondary">Selected pieces</p><h2 className="mt-3 font-display text-4xl text-raoza-primary md:text-6xl">The current edit.</h2></div><Link href="/shop" className="hidden text-xs uppercase tracking-[.17em] underline underline-offset-8 sm:block">View all</Link></div>{featuredProducts.length?<div className="grid grid-cols-2 gap-x-4 gap-y-12 lg:grid-cols-4 lg:gap-x-6">{featuredProducts.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<div className="border-y border-raoza-primary/15 py-20 text-center"><p className="font-display text-3xl text-raoza-primary">The first RAOZA pieces are being prepared.</p><p className="mt-3 text-sm text-raoza-black/55">Published products will appear here automatically.</p></div>}</section>
  <section className="bg-raoza-black text-raoza-cream"><div className="mx-auto grid max-w-[1500px] gap-12 px-5 py-20 md:px-10 lg:grid-cols-2"><p className="font-display text-5xl leading-[.95] md:text-7xl">Not a print shop.<br/><span className="italic text-raoza-gold">A point of view.</span></p><div className="flex max-w-lg flex-col justify-end"><p className="text-base leading-8 text-raoza-cream/70">RAOZA is built as a design-led apparel label: a controlled product selection, considered graphics and a visual identity that can grow beyond the first printed pieces.</p></div></div></section>
  {collections.length>0&&<section className="mx-auto max-w-[1500px] px-5 py-20 md:px-10"><p className="text-[10px] uppercase tracking-[.22em] text-raoza-secondary">Collections</p><div className="mt-8 grid gap-px bg-raoza-primary/20 md:grid-cols-3">{collections.map((c,i)=><Link key={c.id} href={`/collections/${c.slug}`} className="group min-h-72 bg-raoza-cream p-8 flex flex-col justify-between"><span className="text-xs tracking-[.16em]">0{i+1}</span><div><h3 className="font-display text-4xl text-raoza-primary group-hover:italic">{c.name}</h3>{c.description&&<p className="mt-4 text-sm leading-6 text-raoza-black/55">{c.description}</p>}</div></Link>)}</div></section>}
 </main></StorefrontLayout>}
