import { Form, Link } from '@inertiajs/react';
import SeoHead, { Seo } from '../../Components/SeoHead';
import ProductCard, { ProductCardData } from '../../Components/ProductCard';
import StorefrontLayout from '../../Layouts/StorefrontLayout';
type Pagination={data:ProductCardData[];current_page:number;last_page:number;prev_page_url:string|null;next_page_url:string|null;total:number};
export default function Shop({products,query,title,pageType='shop',intro,seo}:{products:Pagination;query:{q:string};title:string;pageType?:'shop'|'category'|'collection';intro?:string|null;seo:Seo}){return <StorefrontLayout><SeoHead seo={seo}/><main>
 <header className="border-b border-raoza-primary/15"><div className="mx-auto grid max-w-[1500px] gap-8 px-5 py-12 md:px-10 md:py-16 lg:grid-cols-[1fr_.7fr] lg:items-end"><div><nav aria-label="Breadcrumb" className="mb-5 flex gap-2 text-[9px] font-semibold uppercase tracking-[.18em] text-raoza-black/50"><Link href="/">Home</Link><span aria-hidden="true">/</span>{pageType!=='shop'&&<><Link href="/shop">Shop</Link><span aria-hidden="true">/</span></>}<span aria-current="page" className="text-raoza-primary">{title}</span></nav><p className="raoza-eyebrow">{pageType==='collection'?'Editorial collection':pageType==='category'?'Product category':'RAOZA / All apparel'}</p><h1 className="mt-3 font-display text-[clamp(3.5rem,7vw,7rem)] leading-[.88] tracking-[-.045em] text-raoza-primary">{title}</h1>{intro&&<p className="mt-5 max-w-xl text-sm leading-7 text-raoza-black/60">{intro}</p>}</div><Form action="/shop" method="get" className="flex border-b border-raoza-primary/35 lg:justify-self-end"><label htmlFor="catalog-search" className="sr-only">Search products</label><input id="catalog-search" name="q" defaultValue={query.q} placeholder="Search the collection" className="w-full bg-transparent py-3 text-sm outline-none sm:w-72"/><button className="px-2 text-[10px] font-semibold uppercase tracking-[.16em]">Search</button></Form></div></header>
 <section className="mx-auto max-w-[1500px] px-5 md:px-10" aria-live="polite"><div className="flex items-center justify-between border-b border-raoza-primary/10 py-5 text-[9px] uppercase tracking-[.18em] text-raoza-black/50"><span>{products.total} {products.total===1?'piece':'pieces'}</span><span>Page {products.current_page} / {products.last_page}</span></div>{products.data.length?<div className="grid grid-cols-2 gap-x-4 gap-y-12 py-8 md:py-10 lg:grid-cols-3 xl:grid-cols-4 lg:gap-x-6">{products.data.map((p,i)=><ProductCard key={p.id} product={p} priority={i<4}/>)}</div>:<div className="py-24 text-center"><h2 className="font-display text-4xl text-raoza-primary">No pieces found.</h2><p className="mt-3 text-sm text-raoza-black/55">{query.q?'Try another search or return to the full shop.':'This selection has no available pieces.'}</p><Link href="/shop" className="raoza-button raoza-button-outline mt-7">{query.q?'Clear search':'View all pieces'}</Link></div>}{(products.prev_page_url||products.next_page_url)&&<nav aria-label="Product pages" className="mt-8 flex justify-center gap-3 border-t border-raoza-primary/10 pt-10">{products.prev_page_url&&<Link href={products.prev_page_url} preserveScroll rel="prev" className="raoza-button raoza-button-outline">Previous</Link>}{products.next_page_url&&<Link href={products.next_page_url} preserveScroll rel="next" className="raoza-button">Next</Link>}</nav>}</section>
 </main></StorefrontLayout>}
