<?php
namespace App\Domain\Returns\Services;
use App\Domain\Commerce\Enums\PaymentStatus;
use App\Domain\Commerce\Enums\FulfillmentStatus;
use App\Domain\Commerce\Models\Order;
use App\Domain\Commerce\Models\OrderItem;
use App\Domain\Inventory\Enums\InventoryMovementType;
use App\Domain\Inventory\Models\Inventory;
use App\Domain\Inventory\Models\InventoryMovement;
use App\Domain\Returns\Enums\ReturnCondition;
use App\Domain\Returns\Enums\ReturnResolution;
use App\Domain\Returns\Enums\ReturnStatus;
use App\Domain\Returns\Models\ReturnItem;
use App\Domain\Returns\Models\ReturnRequest;
use Illuminate\Support\Facades\DB;
use RuntimeException;
class ReturnService {
 public function create(Order $order,array $items,?string $summary=null,?string $customerNote=null):ReturnRequest {
  if(!in_array($order->payment_status,[PaymentStatus::Paid,PaymentStatus::PartiallyRefunded],true))throw new RuntimeException('Only paid orders can enter the return flow.');
  if($order->fulfillment_status!==FulfillmentStatus::Fulfilled)throw new RuntimeException('Only fulfilled orders can enter the physical return flow.');
  if($items===[])throw new RuntimeException('A return must contain at least one item.');
  return DB::transaction(function()use($order,$items,$summary,$customerNote){$locked=Order::whereKey($order->id)->lockForUpdate()->firstOrFail();if(!in_array($locked->payment_status,[PaymentStatus::Paid,PaymentStatus::PartiallyRefunded],true))throw new RuntimeException('Only paid orders can enter the return flow.');if($locked->fulfillment_status!==FulfillmentStatus::Fulfilled)throw new RuntimeException('Only fulfilled orders can enter the physical return flow.');$ret=ReturnRequest::create(['return_number'=>$this->number(),'order_id'=>$locked->id,'status'=>ReturnStatus::Requested,'reason_summary'=>$summary,'customer_note'=>$customerNote,'requested_at'=>now()]);foreach($items as $row){$oi=OrderItem::where('order_id',$locked->id)->whereKey($row['order_item_id'])->firstOrFail();$qty=(int)$row['quantity'];if($qty<1||$qty>$oi->quantity)throw new RuntimeException('Invalid return quantity.');$already=ReturnItem::where('order_item_id',$oi->id)->whereHas('returnRequest',fn($q)=>$q->whereNotIn('status',[ReturnStatus::Rejected->value,ReturnStatus::Cancelled->value]))->sum('quantity');if($already+$qty>$oi->quantity)throw new RuntimeException('Return quantity exceeds the purchased quantity.');$ret->items()->create(['order_item_id'=>$oi->id,'quantity'=>$qty,'reason_code'=>$row['reason_code'],'reason_text'=>$row['reason_text']??null,'resolution'=>ReturnResolution::Pending]);}return $ret->load('items');},3);
 }
 public function transition(ReturnRequest $return,ReturnStatus $to,?string $note=null):ReturnRequest {return DB::transaction(function()use($return,$to,$note){$r=ReturnRequest::whereKey($return->id)->lockForUpdate()->firstOrFail();$allowed=match($r->status){ReturnStatus::Requested=>[ReturnStatus::UnderReview,ReturnStatus::Approved,ReturnStatus::Rejected,ReturnStatus::Cancelled],ReturnStatus::UnderReview=>[ReturnStatus::Approved,ReturnStatus::Rejected,ReturnStatus::Cancelled],ReturnStatus::Approved=>[ReturnStatus::AwaitingReturn,ReturnStatus::Received,ReturnStatus::Cancelled],ReturnStatus::AwaitingReturn=>[ReturnStatus::Received,ReturnStatus::Cancelled],ReturnStatus::Received=>[ReturnStatus::Inspected],ReturnStatus::Inspected=>[ReturnStatus::Completed],default=>[]};if(!in_array($to,$allowed,true))throw new RuntimeException('Invalid return status transition.');if($to===ReturnStatus::Inspected){$pending=$r->items()->where(fn($q)=>$q->whereNull('condition')->orWhere('resolution',ReturnResolution::Pending->value))->exists();if($pending)throw new RuntimeException('Inspect every return item before marking the return as inspected.');}$data=['status'=>$to];if($note!==null)$data['admin_note']=$note;if($to===ReturnStatus::Approved)$data['approved_at']=now();if($to===ReturnStatus::Received)$data['received_at']=now();if($to===ReturnStatus::Completed)$data['completed_at']=now();if($to===ReturnStatus::Cancelled)$data['cancelled_at']=now();$r->update($data);return $r->refresh();},3);}
 public function inspect(ReturnItem $item,ReturnCondition $condition,ReturnResolution $resolution):ReturnItem {return DB::transaction(function()use($item,$condition,$resolution){$i=ReturnItem::whereKey($item->id)->lockForUpdate()->with(['returnRequest','orderItem'])->firstOrFail();if(!in_array($i->returnRequest->status,[ReturnStatus::Received,ReturnStatus::Inspected],true))throw new RuntimeException('Return must be received before inspection.');if($i->restocked_at && $condition!==ReturnCondition::Resellable)throw new RuntimeException('A restocked return item cannot be reclassified as non-resellable without an explicit inventory reversal.');$i->update(['condition'=>$condition,'resolution'=>$resolution]);if($condition===ReturnCondition::Resellable && !$i->restocked_at){$variantId=$i->orderItem->variant_id;if(!$variantId)throw new RuntimeException('Cannot restock an item without its variant.');$inv=Inventory::where('variant_id',$variantId)->lockForUpdate()->firstOrFail();$inv->quantity_on_hand+=$i->quantity;$inv->assertConsistent();$inv->save();InventoryMovement::create(['variant_id'=>$variantId,'type'=>InventoryMovementType::ReturnReceived,'quantity'=>$i->quantity,'reference_type'=>'return_item','reference_id'=>(string)$i->id,'note'=>'Resellable return '.$i->returnRequest->return_number,'created_at'=>now()]);$i->update(['restocked_at'=>now()]);}return $i->refresh();},3);}
 private function number():string {do{$n='RT-'.now()->format('Y').'-'.str_pad((string)random_int(1,999999),6,'0',STR_PAD_LEFT);}while(ReturnRequest::where('return_number',$n)->exists());return $n;}
}
