import {router,usePage} from '@inertiajs/react';
import {useEffect,useState} from 'react';
export default function ConsentBanner(){
 const p:any=usePage(); const current=p.props.consent??{};
 const [visible,setVisible]=useState(!current.decided); const [details,setDetails]=useState(false); const [analytics,setAnalytics]=useState(!!current.analytics); const [marketing,setMarketing]=useState(!!current.marketing);
 useEffect(()=>{const open=()=>{setAnalytics(!!current.analytics);setMarketing(!!current.marketing);setDetails(true);setVisible(true)};window.addEventListener('raoza:cookie-preferences',open);return()=>window.removeEventListener('raoza:cookie-preferences',open)},[current.analytics,current.marketing]);
 if(!visible)return null;
 const save=(a:boolean,m:boolean)=>router.post('/consent',{analytics:a,marketing:m},{preserveScroll:true,onSuccess:()=>setVisible(false)});
 return <div className="fixed inset-x-3 bottom-3 z-[80] mx-auto max-h-[calc(100svh-1.5rem)] max-w-3xl overflow-y-auto border border-raoza-primary/20 bg-raoza-cream p-5 shadow-2xl" role="dialog" aria-labelledby="consent-title" aria-describedby="consent-description">
  <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p id="consent-title" className="font-display text-2xl text-raoza-primary">Your privacy choices.</p><p id="consent-description" className="mt-1 text-xs leading-5 text-raoza-black/60">Necessary cookies keep the store working. Analytics and marketing stay off unless you choose them. <a href="/pages/cookies" className="underline underline-offset-2">Read the cookie policy</a>.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>save(false,false)} className="min-h-11 border border-raoza-primary px-4 py-2 text-[10px] uppercase tracking-widest">Necessary only</button><button type="button" onClick={()=>setDetails(!details)} aria-expanded={details} className="min-h-11 border border-raoza-primary px-4 py-2 text-[10px] uppercase tracking-widest">Choose</button><button type="button" onClick={()=>save(true,true)} className="min-h-11 bg-raoza-primary px-4 py-2 text-[10px] uppercase tracking-widest text-raoza-cream">Accept all</button></div></div>
  {details&&<div className="mt-4 space-y-3 border-t border-raoza-primary/15 pt-4 text-sm"><label className="flex min-h-11 items-center justify-between gap-4"><span><b>Necessary</b><span className="block text-xs text-raoza-black/55">Required for cart, checkout and security.</span></span><input type="checkbox" checked disabled aria-label="Necessary cookies enabled"/></label><label className="flex min-h-11 items-center justify-between gap-4"><span><b>Analytics</b><span className="block text-xs text-raoza-black/55">Helps measure store usage when an analytics provider is configured.</span></span><input type="checkbox" checked={analytics} onChange={e=>setAnalytics(e.target.checked)}/></label><label className="flex min-h-11 items-center justify-between gap-4"><span><b>Marketing</b><span className="block text-xs text-raoza-black/55">Allows marketing measurement when a marketing provider is configured.</span></span><input type="checkbox" checked={marketing} onChange={e=>setMarketing(e.target.checked)}/></label><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>save(analytics,marketing)} className="raoza-button mt-2">Save choices</button>{current.decided&&<button type="button" onClick={()=>setVisible(false)} className="raoza-button raoza-button-outline mt-2">Close</button>}</div></div>}
 </div>
}
