import { Head, useForm } from '@inertiajs/react';
import { useState } from 'react';
import AdminLayout from '../../../Layouts/AdminLayout';

const field = 'mt-1 min-h-11 w-full border border-raoza-primary/20 p-3 text-sm';
type Section = { heading: string; body: string };

export default function ContentIndex({ pages }: { pages: any[] }) {
    const [edit, setEdit] = useState<any>(null);
    const create = useForm({ key: '', title: '', slug: '', seo_title: '', seo_description: '' });
    const form = useForm({ title: '', slug: '', status: 'draft', seo_title: '', seo_description: '', canonical_url: '', og_image: '', indexable: true, content: { intro: '', sections: [] as Section[] } });
    const load = (page: any) => { setEdit(page); form.setData({ title: page.title, slug: page.slug, status: page.status, seo_title: page.seo_title ?? '', seo_description: page.seo_description ?? '', canonical_url: page.canonical_url ?? '', og_image: page.og_image ?? '', indexable: page.indexable, content: { intro: page.content?.intro ?? '', sections: Array.isArray(page.content?.sections) ? page.content.sections : [] } }); };
    const sections = form.data.content.sections;
    const updateSection = (index: number, patch: Partial<Section>) => form.setData('content', { ...form.data.content, sections: sections.map((section, position) => position === index ? { ...section, ...patch } : section) });
    return <AdminLayout><Head title="Content" />
        <div><p className="text-xs uppercase tracking-[.18em] text-raoza-secondary">Marketing</p><h1 className="mt-2 font-display text-4xl text-raoza-primary sm:text-5xl">Content</h1><p className="mt-2 max-w-2xl text-sm text-raoza-black/55">Manage supported information pages, publication and search presentation without editing structured data or source files.</p></div>
        <div className="mt-8 grid gap-8 xl:grid-cols-[.8fr_1.2fr]"><div><div className="overflow-x-auto border bg-white"><table className="w-full min-w-[520px] text-left text-sm"><thead className="bg-raoza-primary text-raoza-cream"><tr><th className="p-3">Page</th><th>Status</th><th>Index</th><th></th></tr></thead><tbody>{pages.map(page => <tr key={page.id} className="border-t"><td className="p-3"><b>{page.title}</b><div className="text-xs opacity-50">/{page.slug}</div></td><td>{page.status}</td><td>{page.indexable ? 'Yes' : 'No'}</td><td><button onClick={() => load(page)} className="min-h-11 px-3 underline">Edit</button></td></tr>)}</tbody></table></div>
                <form onSubmit={e => { e.preventDefault(); create.post('/admin/content/pages', { preserveScroll: true, onSuccess: () => create.reset() }); }} className="mt-6 border bg-white p-5"><h2 className="font-display text-2xl">New controlled page</h2><div className="mt-4 space-y-3"><label className="block text-sm">Internal key<input className={field} value={create.data.key} onChange={e => create.setData('key', e.target.value)} placeholder="e.g. size-guide" /></label><label className="block text-sm">Title<input className={field} value={create.data.title} onChange={e => create.setData('title', e.target.value)} /></label><label className="block text-sm">Slug<input className={field} value={create.data.slug} onChange={e => create.setData('slug', e.target.value)} /></label><label className="block text-sm">SEO title<input className={field} value={create.data.seo_title} onChange={e => create.setData('seo_title', e.target.value)} /></label><label className="block text-sm">Meta description<textarea className={field} value={create.data.seo_description} onChange={e => create.setData('seo_description', e.target.value)} /></label></div>{Object.keys(create.errors).length > 0 && <p role="alert" className="mt-3 text-sm text-red-800">{Object.values(create.errors)[0]}</p>}<button disabled={create.processing} className="mt-4 min-h-12 bg-raoza-primary px-5 text-xs uppercase tracking-widest text-raoza-cream">Create draft</button></form></div>
            {edit ? <form onSubmit={e => { e.preventDefault(); form.patch(`/admin/content/pages/${edit.id}`, { preserveScroll: true, onSuccess: () => setEdit(null) }); }} className="h-fit border bg-white p-5 sm:p-6"><div className="flex justify-between"><div><p className="text-xs uppercase tracking-widest text-raoza-secondary">Page editor</p><h2 className="mt-1 font-display text-2xl">{edit.title}</h2></div><button type="button" onClick={() => setEdit(null)} className="text-sm underline">Close</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm">Title<input className={field} value={form.data.title} onChange={e => form.setData('title', e.target.value)} /></label><label className="text-sm">Slug<input className={field} value={form.data.slug} onChange={e => form.setData('slug', e.target.value)} /></label><label className="text-sm">Status<select className={field} value={form.data.status} onChange={e => form.setData('status', e.target.value)}><option value="draft">Draft</option><option value="published">Published</option></select></label><label className="flex min-h-11 items-center gap-2 self-end text-sm"><input type="checkbox" checked={form.data.indexable} onChange={e => form.setData('indexable', e.target.checked)} />Allow search indexing</label><label className="text-sm sm:col-span-2">Page introduction<textarea rows={4} className={field} value={form.data.content.intro} onChange={e => form.setData('content', { ...form.data.content, intro: e.target.value })} /></label></div>
                <section className="mt-6"><div className="flex items-center justify-between"><h3 className="font-semibold">Content sections</h3><button type="button" onClick={() => form.setData('content', { ...form.data.content, sections: [...sections, { heading: '', body: '' }] })} className="min-h-11 border px-3 text-sm">Add section</button></div><div className="mt-3 space-y-4">{sections.map((section, index) => <div key={index} className="border p-4"><div className="flex justify-between"><b className="text-sm">Section {index + 1}</b><button type="button" onClick={() => form.setData('content', { ...form.data.content, sections: sections.filter((_, position) => position !== index) })} className="text-xs text-red-800 underline">Remove</button></div><label className="mt-3 block text-sm">Heading<input className={field} value={section.heading} onChange={e => updateSection(index, { heading: e.target.value })} /></label><label className="mt-3 block text-sm">Body<textarea rows={5} className={field} value={section.body} onChange={e => updateSection(index, { body: e.target.value })} /></label></div>)}{sections.length === 0 && <div className="border border-dashed p-5 text-sm opacity-55">No sections yet. The introduction can be used on its own.</div>}</div></section>
                <section className="mt-6 border-t pt-5"><h3 className="font-semibold">SEO & sharing</h3><div className="mt-3 grid gap-4 sm:grid-cols-2"><label className="text-sm">SEO title<input className={field} value={form.data.seo_title} onChange={e => form.setData('seo_title', e.target.value)} /></label><label className="text-sm">Canonical URL<input className={field} value={form.data.canonical_url} onChange={e => form.setData('canonical_url', e.target.value)} /></label><label className="text-sm sm:col-span-2">Meta description<textarea className={field} value={form.data.seo_description} onChange={e => form.setData('seo_description', e.target.value)} /></label><label className="text-sm sm:col-span-2">Open Graph image path or URL<input className={field} value={form.data.og_image} onChange={e => form.setData('og_image', e.target.value)} /></label></div></section>{Object.keys(form.errors).length > 0 && <p role="alert" className="mt-4 text-sm text-red-800">{Object.values(form.errors)[0]}</p>}<button disabled={form.processing} className="mt-5 min-h-12 bg-raoza-primary px-5 text-xs uppercase tracking-widest text-raoza-cream">{form.processing ? 'Saving…' : 'Save page'}</button></form> : <div className="h-fit border border-dashed p-8 text-sm text-raoza-black/50">Select a page to edit its readable content, publication and SEO settings.</div>}
        </div>
    </AdminLayout>;
}
