import { Head, useForm } from '@inertiajs/react';
import { useState } from 'react';
import AdminLayout from '../../../Layouts/AdminLayout';

const field = 'mt-1 min-h-11 w-full border border-raoza-primary/20 bg-white px-3 py-2 text-sm';
const initial = (category: boolean) => ({ name: '', slug: '', status: category ? 'active' : 'draft', position: 0, parent_id: '' as any, description: '', seo_title: '', seo_description: '', canonical_url: '', indexable: true, product_ids: [] as number[] });

export default function TaxonomyIndex({ kind, items, products }: any) {
    const isCategory = kind === 'Categories';
    const [edit, setEdit] = useState<any>(null);
    const form = useForm(initial(isCategory));
    const reset = () => { setEdit(null); form.setData(initial(isCategory)); form.clearErrors(); };
    const load = (item: any) => { setEdit(item); form.setData({ name: item.name, slug: item.slug, status: item.status, position: item.position ?? 0, parent_id: item.parent_id ?? '', description: item.description ?? '', seo_title: item.seo_title ?? '', seo_description: item.seo_description ?? '', canonical_url: item.canonical_url ?? '', indexable: item.indexable ?? true, product_ids: (item.products ?? []).map((product: any) => product.id) }); };
    const submit = (event: React.FormEvent) => { event.preventDefault(); const base = isCategory ? '/admin/categories' : '/admin/collections'; edit ? form.patch(`${base}/${edit.id}`, { preserveScroll: true, onSuccess: reset }) : form.post(base, { preserveScroll: true, onSuccess: reset }); };
    const toggleProduct = (id: number) => form.setData('product_ids', form.data.product_ids.includes(id) ? form.data.product_ids.filter(value => value !== id) : [...form.data.product_ids, id]);

    return <AdminLayout><Head title={kind} />
        <div><p className="text-xs uppercase tracking-[.18em] text-raoza-secondary">Catalog</p><h1 className="mt-2 font-display text-4xl text-raoza-primary sm:text-5xl">{kind}</h1><p className="mt-2 max-w-2xl text-sm text-raoza-black/55">{isCategory ? 'Manage permanent browsing structure, product assignments and search metadata.' : 'Manage editorial product stories, publication and product assignments.'}</p></div>
        <div className="mt-8 grid gap-8 xl:grid-cols-[1fr_.9fr]">
            <div className="space-y-3">{items.map((item: any) => <article className="border border-raoza-primary/15 bg-white p-4" key={item.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{item.name}</h2><p className="mt-1 text-xs opacity-55">/{item.slug}{isCategory && item.parent ? ` · under ${item.parent.name}` : ''}</p></div><span className="border px-2 py-1 text-[10px] uppercase tracking-wider">{item.status}</span></div><p className="mt-3 text-sm text-raoza-black/60">{item.description || 'No description yet.'}</p><div className="mt-4 flex items-center justify-between border-t pt-3 text-xs"><span>{item.products_count ?? 0} product{item.products_count === 1 ? '' : 's'}</span><button onClick={() => load(item)} className="min-h-11 px-3 underline">Edit & assign</button></div></article>)}{items.length === 0 && <div className="border border-dashed p-8 text-sm opacity-60">No {kind.toLowerCase()} yet. Create the first one using the form.</div>}</div>
            <form onSubmit={submit} className="h-fit border border-raoza-primary/15 bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-widest text-raoza-secondary">{edit ? 'Editing' : 'Create'}</p><h2 className="mt-1 font-display text-2xl">{edit ? edit.name : `New ${isCategory ? 'category' : 'collection'}`}</h2></div>{edit && <button type="button" onClick={reset} className="text-sm underline">Cancel</button>}</div>
                <div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Name *<input required className={field} value={form.data.name} onChange={e => form.setData('name', e.target.value)} /></label><label className="text-sm font-medium">Slug<input className={field} value={form.data.slug} onChange={e => form.setData('slug', e.target.value)} placeholder="Generated when empty" /></label>
                    {isCategory && <><label className="text-sm font-medium">Parent<select className={field} value={form.data.parent_id} onChange={e => form.setData('parent_id', e.target.value)}><option value="">No parent</option>{items.filter((item: any) => item.id !== edit?.id).map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-medium">Display order<input type="number" min="0" className={field} value={form.data.position} onChange={e => form.setData('position', Number(e.target.value))} /></label></>}
                    <label className="text-sm font-medium">Status<select className={field} value={form.data.status} onChange={e => form.setData('status', e.target.value)}>{(isCategory ? ['active', 'inactive'] : ['draft', 'active', 'archived']).map(value => <option key={value} value={value}>{value}</option>)}</select></label>
                    <label className="flex min-h-11 items-center gap-2 self-end text-sm"><input type="checkbox" checked={form.data.indexable} onChange={e => form.setData('indexable', e.target.checked)} />Allow search indexing</label>
                    <label className="text-sm font-medium sm:col-span-2">Description<textarea rows={4} className={field} value={form.data.description} onChange={e => form.setData('description', e.target.value)} /></label>
                    <label className="text-sm font-medium">SEO title<input className={field} value={form.data.seo_title} onChange={e => form.setData('seo_title', e.target.value)} /></label><label className="text-sm font-medium">Canonical URL<input type="url" className={field} value={form.data.canonical_url} onChange={e => form.setData('canonical_url', e.target.value)} /></label><label className="text-sm font-medium sm:col-span-2">Meta description<textarea rows={3} className={field} value={form.data.seo_description} onChange={e => form.setData('seo_description', e.target.value)} /></label>
                </div>
                <fieldset className="mt-6"><legend className="text-sm font-semibold">Assigned products</legend><p className="mt-1 text-xs opacity-55">Changes are applied safely to catalog relationships when saved.</p><div className="mt-3 max-h-72 space-y-2 overflow-y-auto border p-2">{products.map((product: any) => <label key={product.id} className="flex min-h-11 items-center gap-3 border px-3 py-2 text-sm"><input type="checkbox" checked={form.data.product_ids.includes(product.id)} onChange={() => toggleProduct(product.id)} /><span>{product.name}</span><span className="ml-auto text-xs opacity-50">{product.status}</span></label>)}</div></fieldset>
                {Object.keys(form.errors).length > 0 && <div role="alert" className="mt-4 border border-red-700/30 bg-red-50 p-3 text-sm text-red-900">{Object.values(form.errors)[0] as string}</div>}
                <button disabled={form.processing || !form.data.name} className="mt-5 min-h-12 w-full bg-raoza-primary px-5 text-xs uppercase tracking-widest text-raoza-cream disabled:opacity-40">{form.processing ? 'Saving…' : edit ? 'Save changes' : `Create ${isCategory ? 'category' : 'collection'}`}</button>
            </form>
        </div>
    </AdminLayout>;
}
