import React, {useState} from 'react';
import {Head, Link, router, usePage} from '@inertiajs/react';
import AdminLayout from '../../../Layouts/AdminLayout';

type Item={id:number;name:string;sku:string;quantity:number;condition:string|null;resolution:string;restocked:boolean};
type Refund={id:number;amount:number;status:string;reason:string|null;requested_at:string|null};
type ReturnRow={return_number:string;order_number:string;email:string;currency:string;order_total:number;status:string;requested_at:string|null;admin_note:string|null;items:Item[];refunds:Refund[]};
const next:Record<string,string[]>={requested:['under_review','approved','rejected','cancelled'],under_review:['approved','rejected','cancelled'],approved:['awaiting_return','received','cancelled'],awaiting_return:['received','cancelled'],received:['inspected'],inspected:['completed']};
const eur=(n:number)=>(n/100).toLocaleString('nl-NL',{style:'currency',currency:'EUR'});
const label=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export default function ReturnsIndex({returns}:{returns:ReturnRow[]}){
 const page=usePage<any>(); const [busy,setBusy]=useState<string|null>(null); const [amounts,setAmounts]=useState<Record<string,string>>({});
 const errors=page.props.errors??{};
 const move=(n:string,status:string)=>{setBusy(`${n}:${status}`);router.patch(`/admin/returns/${n}`,{status},{preserveScroll:true,onFinish:()=>setBusy(null)});};
 const inspect=(id:number,condition:string,resolution:string)=>{setBusy(`item:${id}`);router.patch(`/admin/return-items/${id}/inspection`,{condition,resolution},{preserveScroll:true,onFinish:()=>setBusy(null)});};
 const refund=(r:ReturnRow)=>{const raw=amounts[r.return_number]??'';const cents=Math.round(Number(raw.replace(',','.'))*100);if(!Number.isFinite(cents)||cents<1)return;setBusy(`refund:${r.return_number}`);router.post(`/admin/orders/${r.order_number}/refunds`,{amount:cents,return_number:r.return_number,reason:`Return ${r.return_number}`},{preserveScroll:true,onFinish:()=>setBusy(null)});};
 return <AdminLayout><Head title="Returns — RAOZA Admin"/><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.22em] text-[#602032]">RAOZA Admin</p><h1 className="mt-2 font-display text-4xl text-[#330313]">Returns & refunds</h1></div><Link href="/admin/orders" className="border border-[#330313] px-4 py-2 text-sm">Orders</Link></div>
 {(errors.return||errors.refund)&&<div role="alert" className="mt-5 border border-red-700/25 bg-red-50 p-3 text-sm text-red-900">{errors.return||errors.refund}</div>}
 <div className="mt-8 space-y-5">{returns.length===0?<div className="border border-[#330313]/15 bg-white/50 p-8 text-sm opacity-70">No returns yet. Create a return from a fulfilled order.</div>:returns.map(r=><section key={r.return_number} className="border border-[#330313]/15 bg-white/50 p-5"><div className="flex flex-wrap justify-between gap-3"><div><strong>{r.return_number}</strong> · <Link className="underline" href={`/admin/orders/${r.order_number}`}>{r.order_number}</Link><div className="text-sm opacity-70">{r.email}</div></div><span className="text-xs uppercase tracking-wider">{label(r.status)}</span></div>
 <div className="mt-4 space-y-3">{r.items.map(i=><div key={i.id} className="border-t border-[#330313]/10 pt-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><span>{i.name} · {i.sku} · ×{i.quantity}</span><span className="opacity-65">{i.condition?label(i.condition):'Not inspected'} · {label(i.resolution)}{i.restocked?' · Restocked':''}</span></div>{['received','inspected'].includes(r.status)&&<div className="mt-2"><div className="flex flex-wrap gap-2"><button disabled={busy!==null} onClick={()=>inspect(i.id,'resellable','refund')} className="border px-3 py-1 disabled:opacity-40">Resellable + refund</button><button disabled={busy!==null||i.restocked} onClick={()=>inspect(i.id,'damaged','refund')} className="border px-3 py-1 disabled:cursor-not-allowed disabled:opacity-40">Damaged + refund</button><button disabled={busy!==null||i.restocked} onClick={()=>inspect(i.id,'other','no_refund')} className="border px-3 py-1 disabled:cursor-not-allowed disabled:opacity-40">Other / no refund</button></div>{i.restocked&&<p className="mt-2 text-xs opacity-60">Restocked items cannot be reclassified as non-resellable without an explicit inventory reversal.</p>}</div>}</div>)}</div>
 {(next[r.status]??[]).length>0&&<div className="mt-4 flex flex-wrap gap-2">{next[r.status].map(s=><button key={s} disabled={busy!==null} onClick={()=>move(r.return_number,s)} className="bg-[#330313] px-3 py-2 text-xs uppercase tracking-wider text-[#FFF6E6] disabled:opacity-40">{label(s)}</button>)}</div>}
 {r.refunds.length>0&&<div className="mt-5 border-t pt-4"><div className="text-xs font-semibold uppercase tracking-wider">Refund history</div>{r.refunds.map(x=><div key={x.id} className="mt-2 flex flex-wrap justify-between gap-2 text-sm"><span>{eur(x.amount)} · {label(x.status)}</span><span className="opacity-60">{x.reason||'—'}</span></div>)}</div>}
 {['inspected','completed'].includes(r.status)&&<div className="mt-5 border-t pt-4"><div className="text-xs font-semibold uppercase tracking-wider">Request refund</div><p className="mt-1 text-xs opacity-60">Creates a refund request only. Money is not considered refunded until the payment provider confirms success.</p><div className="mt-3 flex max-w-md gap-2"><label className="sr-only" htmlFor={`refund-${r.return_number}`}>Refund amount in EUR</label><input id={`refund-${r.return_number}`} inputMode="decimal" value={amounts[r.return_number]??''} onChange={e=>setAmounts({...amounts,[r.return_number]:e.target.value})} placeholder="Amount in EUR" className="min-w-0 flex-1 border bg-white px-3 py-2"/><button disabled={busy!==null} onClick={()=>refund(r)} className="bg-[#330313] px-4 py-2 text-sm text-[#FFF6E6] disabled:opacity-40">Request refund</button></div></div>}
 </section>)}</div></div></AdminLayout>;
}
