import { Head, Link } from '@inertiajs/react';
import AdminLayout from '../../../Layouts/AdminLayout';

const eur = (value: number) => (value / 100).toLocaleString('nl-NL', { style: 'currency', currency: 'EUR' });
const date = (value?: string) => value ? new Date(value).toLocaleString('nl-NL') : '—';
const text = (value: any) => typeof value === 'string' ? value : value?.value ?? String(value ?? '—');

export default function CustomerShow({ customer }: any) {
    return <AdminLayout><Head title={`${customer.name || customer.email} — Customer`} />
        <Link href="/admin/customers" className="text-sm underline">← Customers</Link>
        <div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.18em] text-raoza-secondary">Customer record</p><h1 className="mt-2 font-display text-4xl text-raoza-primary sm:text-5xl">{customer.name || 'Name unavailable'}</h1><p className="mt-2 break-all text-sm opacity-65">{customer.email}</p></div><span className="border px-3 py-2 text-xs uppercase tracking-widest">{customer.account ? 'Account customer' : 'Guest checkout'}</span></div>
        <div className="mt-8 grid gap-5 lg:grid-cols-3"><section className="border bg-white p-5"><h2 className="font-display text-2xl">Contact</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-xs uppercase tracking-wider opacity-50">Name</dt><dd>{customer.name || 'Not collected'}</dd></div><div><dt className="text-xs uppercase tracking-wider opacity-50">Email</dt><dd className="break-all">{customer.email}</dd></div><div><dt className="text-xs uppercase tracking-wider opacity-50">Phone</dt><dd>{customer.phone || 'Not collected'}</dd></div></dl></section><section className="border bg-white p-5"><h2 className="font-display text-2xl">Account</h2><p className="mt-4 text-sm">{customer.account ? `Registered ${date(customer.account.created_at)}` : 'This customer used guest checkout. No account is required.'}</p></section><section className="border bg-white p-5"><h2 className="font-display text-2xl">Paid history</h2><p className="mt-4 font-display text-4xl text-raoza-primary">{eur(customer.lifetime_value)}</p><p className="mt-2 text-sm opacity-60">{customer.paid_orders_count} paid order{customer.paid_orders_count === 1 ? '' : 's'}</p></section></div>
        <section className="mt-6 border bg-white p-5"><h2 className="font-display text-2xl">Known order addresses</h2><p className="mt-1 text-xs opacity-55">Shown only from completed checkout data; duplicates are removed.</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{customer.addresses.map((address: any, index: number) => <address key={index} className="border p-4 text-sm not-italic leading-6"><b className="text-xs uppercase tracking-wider">{address.type}</b><div className="mt-2">{address.first_name} {address.last_name}</div>{address.company && <div>{address.company}</div>}<div>{address.street} {address.house_number}{address.addition ? ` ${address.addition}` : ''}</div><div>{address.postal_code} {address.city}</div><div>{address.country_code}</div></address>)}</div></section>
        <section className="mt-6"><h2 className="font-display text-3xl">Order history</h2><div className="mt-4 overflow-x-auto border bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-raoza-primary text-raoza-cream"><tr><th className="p-3">Order</th><th>Date</th><th>Payment</th><th>Order</th><th>Fulfillment</th><th>Total</th></tr></thead><tbody>{customer.orders.map((order: any) => <tr className="border-t" key={order.order_number}><td className="p-3"><Link href={`/admin/orders/${order.order_number}`} className="font-medium underline">{order.order_number}</Link></td><td>{date(order.placed_at)}</td><td>{text(order.payment_status)}</td><td>{text(order.order_status)}</td><td>{text(order.fulfillment_status)}</td><td>{eur(order.total_amount)}</td></tr>)}</tbody></table></div></section>
    </AdminLayout>;
}
