<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void {
 Schema::table('orders',function(Blueprint $t){$t->boolean('analytics_consent')->default(false)->after('customer_phone');$t->boolean('marketing_consent')->default(false)->after('analytics_consent');});
 Schema::table('products',function(Blueprint $t){$t->string('canonical_url')->nullable()->after('seo_description');$t->string('og_image')->nullable()->after('canonical_url');$t->boolean('indexable')->default(true)->after('og_image');});
 Schema::table('collections',function(Blueprint $t){$t->string('seo_title')->nullable()->after('description');$t->text('seo_description')->nullable()->after('seo_title');$t->string('canonical_url')->nullable()->after('seo_description');$t->string('og_image')->nullable()->after('canonical_url');$t->boolean('indexable')->default(true)->after('og_image');});
 Schema::create('content_pages',function(Blueprint $t){$t->id();$t->string('key')->unique();$t->string('title');$t->string('slug')->unique();$t->string('status',24)->default('draft')->index();$t->jsonb('content')->nullable();$t->string('seo_title')->nullable();$t->text('seo_description')->nullable();$t->string('canonical_url')->nullable();$t->string('og_image')->nullable();$t->boolean('indexable')->default(true);$t->timestampTz('published_at')->nullable()->index();$t->timestampsTz();});
 Schema::create('site_content',function(Blueprint $t){$t->id();$t->string('key')->unique();$t->jsonb('value');$t->timestampsTz();});
 Schema::create('consent_records',function(Blueprint $t){$t->id();$t->uuid('consent_id')->unique();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->boolean('analytics')->default(false);$t->boolean('marketing')->default(false);$t->string('policy_version',32);$t->string('locale',10)->default('en');$t->timestampTz('consented_at');$t->timestampsTz();});
 Schema::create('analytics_events',function(Blueprint $t){$t->id();$t->uuid('event_id')->unique();$t->string('event_name',64)->index();$t->foreignId('order_id')->nullable()->constrained()->nullOnDelete();$t->string('session_hash',64)->nullable()->index();$t->jsonb('payload')->nullable();$t->timestampTz('occurred_at');$t->timestampsTz();});
 }
 public function down():void {Schema::table('orders',fn(Blueprint $t)=>$t->dropColumn(['analytics_consent','marketing_consent']));Schema::dropIfExists('analytics_events');Schema::dropIfExists('consent_records');Schema::dropIfExists('site_content');Schema::dropIfExists('content_pages');Schema::table('collections',fn(Blueprint $t)=>$t->dropColumn(['seo_title','seo_description','canonical_url','og_image','indexable']));Schema::table('products',fn(Blueprint $t)=>$t->dropColumn(['canonical_url','og_image','indexable']));}
};