import { useState } from 'react';
import { Head, Link, router, usePage } from '@inertiajs/react';
import AdminLayout from '../../../Layouts/AdminLayout';

const eur = (value: number) => (value / 100).toLocaleString('nl-NL', { style: 'currency', currency: 'EUR' });
const text = (value: any) => typeof value === 'string' ? value : value?.value ?? String(value ?? '—');
const date = (value?: string) => value ? new Date(value).toLocaleString('nl-NL') : '—';
const imageUrl = (path: string) => path.startsWith('http') || path.startsWith('/') ? path : `/storage/${path}`;

function Address({ title, address }: any) {
    return <section className="border bg-white p-5"><h2 className="font-display text-2xl">{title}</h2>{address ? <address className="mt-3 text-sm not-italic leading-6"><div>{address.first_name} {address.last_name}</div>{address.company && <div>{address.company}</div>}<div>{address.street} {address.house_number}{address.addition ? ` ${address.addition}` : ''}</div><div>{address.postal_code} {address.city}</div><div>{address.country_code}</div></address> : <p className="mt-3 text-sm opacity-60">Same as shipping address.</p>}</section>;
}

export default function OrderShow({ order }: any) {
    const page = usePage<any>();
    const [returnQty, setReturnQty] = useState<Record<number, number>>({});
    const [reason, setReason] = useState('changed_mind');
    const [busy, setBusy] = useState(false);
    const shipping = order.addresses?.find((address: any) => address.type === 'shipping') ?? order.addresses?.[0];
    const billing = order.addresses?.find((address: any) => address.type === 'billing');
    const createReturn = () => {
        const items = order.items.filter((item: any) => (returnQty[item.id] ?? 0) > 0).map((item: any) => ({ order_item_id: item.id, quantity: returnQty[item.id], reason_code: reason }));
        if (!items.length) return;
        setBusy(true);
        router.post(`/admin/orders/${order.order_number}/returns`, { reason_summary: reason, items }, { preserveScroll: true, onFinish: () => setBusy(false) });
    };

    return <AdminLayout><Head title={order.order_number} />
        <div className="flex flex-wrap items-end justify-between gap-4"><div><Link href="/admin/orders" className="text-sm underline">← Orders</Link><h1 className="mt-2 break-all font-display text-4xl text-raoza-primary sm:text-5xl">{order.order_number}</h1><p className="mt-2 text-sm opacity-65">Placed {date(order.placed_at)} · <Link className="underline" href={`/admin/customers/${encodeURIComponent(order.customer_email)}`}>{order.customer_email}</Link>{order.customer_phone ? ` · ${order.customer_phone}` : ''}</p></div><Link href="/admin/fulfillment" className="min-h-11 border border-raoza-primary px-4 py-3 text-sm">Open production & shipping</Link></div>
        <div className="mt-6 grid gap-4 lg:grid-cols-3">
            <section className="border bg-white p-5 lg:col-span-2"><h2 className="font-display text-2xl">Items</h2>{order.items.map((item: any) => <div className="mt-3 grid grid-cols-[64px_1fr_auto] gap-3 border-t pt-3" key={item.id}><div className="h-16 w-16 overflow-hidden rounded-full bg-raoza-cream">{item.product?.images?.[0] && <img src={imageUrl(item.product.images[0].path)} alt="" className="h-full w-full object-cover" />}</div><div><div><b>{item.product_name}</b> × {item.quantity}</div><div className="mt-1 text-xs opacity-60">SKU {item.sku}{item.variant_options ? ` · ${Object.values(item.variant_options).join(' / ')}` : ''}</div><div className="mt-1 text-xs">{eur(item.unit_price)} each</div></div><b>{eur(item.total_amount)}</b></div>)}<div className="mt-5 space-y-1 border-t pt-4 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{eur(order.subtotal_amount)}</span></div><div className="flex justify-between"><span>Discount {order.discount_code ? `(${order.discount_code})` : ''}</span><span>− {eur(order.discount_amount)}</span></div><div className="flex justify-between"><span>{order.shipping_method_name || 'Shipping'}</span><span>{eur(order.shipping_amount)}</span></div><div className="flex justify-between"><span>VAT included</span><span>{eur(order.tax_amount)}</span></div><div className="flex justify-between pt-2 text-base font-semibold"><span>Total</span><span>{eur(order.total_amount)}</span></div></div></section>
            <section className="border bg-white p-5"><h2 className="font-display text-2xl">Operational status</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-xs uppercase opacity-50">Order</dt><dd>{text(order.order_status)}</dd></div><div><dt className="text-xs uppercase opacity-50">Payment</dt><dd>{text(order.payment_status)}</dd></div><div><dt className="text-xs uppercase opacity-50">Fulfillment</dt><dd>{text(order.fulfillment_status)}</dd></div><div><dt className="text-xs uppercase opacity-50">Paid at</dt><dd>{date(order.paid_at)}</dd></div></dl></section>
            <Address title="Shipping address" address={shipping} /><Address title="Billing address" address={billing} />
            <section className="border bg-white p-5"><h2 className="font-display text-2xl">Shipments</h2>{order.shipments.length === 0 ? <p className="mt-3 text-sm opacity-65">No shipment created yet.</p> : order.shipments.map((shipment: any) => <div key={shipment.id} className="mt-3 border-t pt-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><b>{text(shipment.status)}</b><span>{date(shipment.shipped_at)}</span></div><div className="mt-1">Tracking: {shipment.tracking_number || '—'}</div>{shipment.tracking_url && <a className="underline" href={shipment.tracking_url} target="_blank" rel="noreferrer">Open tracking</a>}</div>)}</section>
            <section className="border bg-white p-5 lg:col-span-3"><h2 className="font-display text-2xl">Create return</h2>{order.fulfillment_status === 'fulfilled' ? <><p className="mt-2 text-sm opacity-65">Select only quantities physically returned. The server prevents over-returning.</p>{page.props.errors?.return && <div role="alert" className="mt-3 border border-red-700/25 bg-red-50 p-3 text-sm text-red-900">{page.props.errors.return}</div>}<div className="mt-4 space-y-2">{order.items.map((item: any) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 border-t pt-3 text-sm"><span>{item.product_name} · {item.sku} · purchased ×{item.quantity}</span><input aria-label={`Return quantity for ${item.product_name}`} type="number" min={0} max={item.quantity} value={returnQty[item.id] ?? 0} onChange={e => setReturnQty({ ...returnQty, [item.id]: Math.max(0, Math.min(item.quantity, Number(e.target.value) || 0)) })} className="min-h-11 w-20 border px-2" /></div>)}</div><div className="mt-4 flex flex-wrap gap-2"><label className="sr-only" htmlFor="return-reason">Return reason</label><select id="return-reason" value={reason} onChange={e => setReason(e.target.value)} className="min-h-11 border bg-white px-3 text-sm"><option value="changed_mind">Changed mind</option><option value="wrong_size">Wrong size</option><option value="damaged">Damaged</option><option value="wrong_item">Wrong item</option><option value="other">Other</option></select><button disabled={busy || !Object.values(returnQty).some(quantity => quantity > 0)} onClick={createReturn} className="min-h-11 bg-raoza-primary px-4 text-sm text-raoza-cream disabled:opacity-40">{busy ? 'Creating…' : 'Create return'}</button><Link href="/admin/returns" className="min-h-11 border border-raoza-primary px-4 py-3 text-sm">Open returns</Link></div></> : <p className="mt-2 text-sm opacity-65">Physical returns become available after the order is fulfilled.</p>}</section>
            <section className="border bg-white p-5 lg:col-span-3"><h2 className="font-display text-2xl">Status history</h2>{order.status_history?.length === 0 ? <p className="mt-3 text-sm opacity-65">No status history yet.</p> : <div className="mt-3 divide-y text-sm">{[...(order.status_history || [])].reverse().map((history: any) => <div key={history.id} className="grid gap-1 py-3 md:grid-cols-[180px_1fr]"><span className="opacity-60">{date(history.created_at)}</span><span>{history.domain}: {history.from_status || '—'} → {history.to_status}{history.reason ? ` · ${history.reason}` : ''}</span></div>)}</div>}</section>
        </div>
    </AdminLayout>;
}
