<?php
namespace App\Http\Controllers;
use App\Domain\Commerce\Models\Order;use App\Domain\Commerce\Services\{CartService,CheckoutService};use App\Domain\Fulfillment\Services\ShippingQuoteService;use App\Http\Middleware\ResolveCart;use Illuminate\Http\{RedirectResponse,Request};use Illuminate\Validation\Rule;use Illuminate\Support\Facades\Mail;use App\Mail\OrderReceivedMail;use Inertia\{Inertia,Response};
class CheckoutController extends Controller {
 public function show(Request $request,CartService $cartService,ShippingQuoteService $shipping):Response|RedirectResponse{$summary=$cartService->summary(ResolveCart::from($request));if($summary['items']->isEmpty())return redirect()->route('cart.show');return Inertia::render('Storefront/Checkout',['checkout'=>['cart'=>$summary,'countries'=>[['code'=>'NL','name'=>'Netherlands']],'shippingMethods'=>$shipping->active(),'vatRateBasisPoints'=>(int)config('commerce.vat_rate_basis_points',2100),'demoMode'=>(bool)config('commerce.demo_mode')]]);}
 public function store(Request $request,CheckoutService $service):RedirectResponse{$data=$request->validate($this->rules());$data['_analytics_consent']=(bool)$request->session()->get('consent.analytics',false);$data['_marketing_consent']=(bool)$request->session()->get('consent.marketing',false);$order=$service->createOrder(ResolveCart::from($request),$data);$request->session()->put('last_order_number',$order->order_number);if($order->wasRecentlyCreated)Mail::to($order->customer_email)->queue(new OrderReceivedMail($order));return redirect()->route('checkout.confirmation',['order'=>$order->order_number]);}
 public function confirmation(Request $request,Order $order):Response{abort_unless($request->session()->get('last_order_number')===$order->order_number,404);return Inertia::render('Storefront/OrderConfirmation',['order'=>$this->present($order->load(['items','payments'])),'demoMode'=>(bool)config('commerce.demo_mode')]);}
 private function rules():array{return ['email'=>['required','email:rfc','max:254'],'phone'=>['nullable','string','max:40'],'shipping_method_id'=>['required','integer','exists:shipping_methods,id'],'discount_code'=>['nullable','string','max:50'],'billing_same_as_shipping'=>['required','boolean'],'shipping_first_name'=>['required','string','max:100'],'shipping_last_name'=>['required','string','max:100'],'shipping_company'=>['nullable','string','max:150'],'shipping_street'=>['required','string','max:150'],'shipping_house_number'=>['required','string','max:32'],'shipping_addition'=>['nullable','string','max:32'],'shipping_postal_code'=>['required','string','max:24'],'shipping_city'=>['required','string','max:120'],'shipping_country_code'=>['required',Rule::in(['NL'])],'billing_first_name'=>['exclude_if:billing_same_as_shipping,true','required','string','max:100'],'billing_last_name'=>['exclude_if:billing_same_as_shipping,true','required','string','max:100'],'billing_company'=>['nullable','string','max:150'],'billing_street'=>['exclude_if:billing_same_as_shipping,true','required','string','max:150'],'billing_house_number'=>['exclude_if:billing_same_as_shipping,true','required','string','max:32'],'billing_addition'=>['nullable','string','max:32'],'billing_postal_code'=>['exclude_if:billing_same_as_shipping,true','required','string','max:24'],'billing_city'=>['exclude_if:billing_same_as_shipping,true','required','string','max:120'],'billing_country_code'=>['exclude_if:billing_same_as_shipping,true','required',Rule::in(['NL'])]];}
 private function present(Order $o):array{return ['number'=>$o->order_number,'email'=>$o->customer_email,'currency'=>$o->currency,'subtotal'=>$o->subtotal_amount,'discount'=>$o->discount_amount,'discountCode'=>$o->discount_code,'shipping'=>$o->shipping_amount,'shippingMethod'=>$o->shipping_method_name,'tax'=>$o->tax_amount,'taxRateBasisPoints'=>$o->tax_rate_basis_points,'total'=>$o->total_amount,'paymentStatus'=>$o->payment_status->value,'orderStatus'=>$o->order_status->value,'fulfillmentStatus'=>$o->fulfillment_status->value,'canPay'=>$o->payment_status->canAcceptPayment(),'latestPaymentStatus'=>$o->payments->sortByDesc('id')->first()?->status?->value,'items'=>$o->items->map(fn($i)=>['name'=>$i->product_name,'options'=>$i->variant_options,'quantity'=>$i->quantity,'total'=>$i->total_amount])->values()];}
}
